// Core character
import { character } from '../palette';

// Voicebanks
import { mikuV2, mikuAppend, mikuV3English, mikuV4Chinese, mikuNT } from '../palette';

// Derivatives
import { sakuraMiku, miku15thAnniversary, miku16thAnniversary, gundam45thMiku, lawson50thMiku } from '../palette';

// Events
import { digitalStars, magicalMirai, mikuExpo, snowMiku } from '../palette';

// Games
import {
  projectSekai,
  virtualSinger,
  leoNeed,
  moreMoreJump,
  vividBadSquad,
  wonderlandsShowtime,
  nightcord,
  deepSeaGirl,
  darkAngel,
  heartHunter,
  powder,
  rollingGirl,
  ghost,
} from '../palette/games';

const alpha = (hex: string, opacity: string): string => `${hex}${opacity}`;

// Map to existing palette colors
const blacks = { void: character.armWarmers.base, base: character.skirt.base, outfit: character.skirt.base, sleeve: character.boots.base };
const stage = { darkness: character.armWarmers.base, spotlight: character.skin.highlight, ambientTeal: character.hair.base, accentPink: character.headphones.cushion, warmAmber: magicalMirai.y2024.outfit.skirtPlaid };
const teals = { classic: character.hair.base, bright: character.hair.highlight, neon: character.hair.bright, stage: character.tie.base };
const pinks = { sekai: character.headphones.cushion, blush: character.skin.blush, soft: character.skin.blush, hot: character.headphones.cushion, pale: character.skin.highlight };
const cyans = { ice: character.hair.tip, bright: character.hair.highlight };
const greys = { slate: character.top.main, steel: character.top.shadow, silver: character.skirt.accessory, platinum: character.skin.highlight };
const foregrounds = { primary: character.skin.highlight, secondary: character.skin.shadow, comment: character.top.shadow, bright: character.skin.highlight };
const accents = { amber: magicalMirai.y2024.outfit.skirtPlaid, gold: magicalMirai.y2025.outfit.jacket, orange: magicalMirai.y2024.outfit.skirtPlaid, coral: character.headphones.cushion };
const semantic = { error: character.marks.tattoo, warning: magicalMirai.y2024.outfit.skirtPlaid, success: character.negi.stalk, info: character.hair.highlight };
const hologram = { cyan: character.hair.bright, purple: magicalMirai.y2023.outfit.pants };
const versionMapping = { identity: character.hair.base, hover: character.hair.highlight, focus: character.hair.tip, types: magicalMirai.y2023.outfit.pants };
const frequencyVisualizer = { bass: character.top.shadow, low: character.top.main, mid: character.hair.base, high: character.hair.highlight, peak: character.hair.tip, ultra: character.hair.bright };
const append = { light: character.hair.highlight, vivid: character.hair.base };
const v4xVoice = { soft: character.hair.highlight, normal: character.hair.base, hard: character.hair.shadow };
const versions = { v2: character.hair.base, v3: character.hair.highlight, v4x: character.hair.bright, nt: magicalMirai.y2024.outfit.skirtPlaid, v6ai: magicalMirai.y2023.outfit.pants };
const digital = { dataStream: character.hair.base, binaryGlow: character.hair.bright, glitch: character.headphones.cushion };
const numberSymbolism = { miku39: { heart: character.headphones.cushion }, tattoo01: { background: character.boots.base, glow: character.hair.base } };
const boosted = { purple: magicalMirai.y2023.outfit.pants, coral: character.headphones.cushion, coralGlow: character.skin.blush };
const iconicPVs = { worldIsMine: { crown: magicalMirai.y2025.outfit.jacket }, melt: { blush: character.skin.blush, warmPink: character.skin.blush }, senbonzakura: { sakuraPink: character.skin.blush } };
const seasonalExpanded = { valentine: { heartRed: character.marks.tattoo } };
const derivativeCharacters = { grayMiku: { hairMid: character.top.shadow } };
const viralHits = { mesmerizer: { mikuTeal: character.hair.base, hypnosis: magicalMirai.y2023.outfit.pants }, vampire: { gothicLavender: magicalMirai.y2023.outfit.pants }, king: { crownGold: magicalMirai.y2025.outfit.jacket } };
const mikuDay = { celebration: { confettiYellow: magicalMirai.y2025.outfit.jacket } };
const artStyles = { mikaPikazo: { primary: character.hair.base, secondary: character.headphones.cushion, triadicCyan: character.hair.bright }, ixima: { techCyan: character.hair.base }, lam: { shockPink: character.headphones.cushion } };
const racingMiku = { team: { gsmTeal: character.hair.base }, y2014: { limeAccent: character.negi.bright }, y2016: { accentPink: character.headphones.cushion }, y2017: { highlightCyan: character.hair.bright, gradientPurple: magicalMirai.y2023.outfit.pants }, y2018: { holoBlue: character.hair.highlight } };
const projectDiva = { ratings: { perfect: character.hair.bright, sad: character.headphones.cushion, worst: character.marks.tattoo, good: magicalMirai.y2024.outfit.skirtPlaid, safe: character.skirt.accessory } };


export const workbenchColors = {
  'editor.background': character.skirt.base,
  'editor.foreground': foregrounds.primary,
  'editorCursor.foreground': character.hairTies.base,
  'editorCursor.background': character.eyes.pupil,
  'editorMultiCursor.primary.foreground': character.hairTies.base,
  'editorMultiCursor.primary.background': character.headphones.frame,
  'editorMultiCursor.secondary.foreground': character.hairTies.outline,
  'editorMultiCursor.secondary.background': character.headphones.frame,
  'editor.lineHighlightBackground': alpha(versionMapping.identity, '12'),
  'editor.lineHighlightBorder': alpha(cyans.ice, '30'),
  'editor.selectionBackground': alpha(miku15thAnniversary.outfit.bodice, '35'), // Strawberry red
  'editor.selectionHighlightBackground': alpha(miku15thAnniversary.accessories.strawberryLeaves, '25'), // Green leaves
  'editor.selectionHighlightBorder': alpha(miku15thAnniversary.outfit.bodice, '40'),
  'editor.wordHighlightBackground': alpha(teals.classic, '20'),
  'editor.wordHighlightBorder': alpha(teals.classic, '40'),
  'editor.wordHighlightStrongBackground': alpha(pinks.sekai, '30'),
  'editor.wordHighlightStrongBorder': alpha(pinks.sekai, '60'),
  'editor.findMatchBackground': alpha(pinks.sekai, '60'),
  'editor.findMatchBorder': alpha(pinks.sekai, '90'),
  'editor.findMatchHighlightBackground': alpha(cyans.ice, '50'),
  'editor.findMatchHighlightBorder': alpha(cyans.ice, '80'),
  'editor.rangeHighlightBackground': alpha(teals.classic, '10'),
  'editor.rangeHighlightBorder': alpha(teals.classic, '30'),
  'editorLineNumber.foreground': character.tie.shadow,
  'editorLineNumber.activeForeground': character.hair.highlight,
  'editorLineNumber.dimmedForeground': frequencyVisualizer.bass,
  'editorIndentGuide.background1': alpha(frequencyVisualizer.bass, '50'),
  'editorIndentGuide.background2': alpha(frequencyVisualizer.low, '55'),
  'editorIndentGuide.background3': alpha(frequencyVisualizer.mid, '60'),
  'editorIndentGuide.background4': alpha(frequencyVisualizer.high, '65'),
  'editorIndentGuide.background5': alpha(frequencyVisualizer.peak, '70'),
  'editorIndentGuide.background6': alpha(frequencyVisualizer.ultra, '75'),
  'editorIndentGuide.activeBackground1': frequencyVisualizer.bass,
  'editorIndentGuide.activeBackground2': frequencyVisualizer.low,
  'editorIndentGuide.activeBackground3': frequencyVisualizer.mid,
  'editorIndentGuide.activeBackground4': frequencyVisualizer.high,
  'editorIndentGuide.activeBackground5': frequencyVisualizer.peak,
  'editorIndentGuide.activeBackground6': frequencyVisualizer.ultra,
  'editorRuler.foreground': frequencyVisualizer.bass,
  'editorWhitespace.foreground': frequencyVisualizer.bass,
  'editorBracketMatch.background': alpha(digital.dataStream, '25'),
  'editorBracketMatch.border': digital.binaryGlow,
  'editorBracketHighlight.foreground1': miku16thAnniversary.outfit.bodiceAccent, // Teal
  'editorBracketHighlight.foreground2': miku16thAnniversary.accessories.starAccents, // Golden
  'editorBracketHighlight.foreground3': miku16thAnniversary.outfit.ribbon, // Teal ribbon
  'editorBracketHighlight.foreground4': miku16thAnniversary.hair.highlight, // Light teal
  'editorBracketHighlight.foreground5': miku16thAnniversary.accessories.wingsGlow, // Wings glow
  'editorBracketHighlight.foreground6': miku16thAnniversary.outfit.lace, // Ethereal white
  'editorBracketHighlight.unexpectedBracket.foreground': boosted.coralGlow,
  'editorBracketPairGuide.background1': alpha(pinks.sekai, '25'),
  'editorBracketPairGuide.background2': alpha(teals.classic, '25'),
  'editorBracketPairGuide.background3': alpha(cyans.ice, '25'),
  'editorBracketPairGuide.background4': alpha(hologram.purple, '25'),
  'editorBracketPairGuide.background5': alpha(teals.neon, '25'),
  'editorBracketPairGuide.background6': alpha(pinks.soft, '25'),
  'editorBracketPairGuide.activeBackground1': alpha(pinks.sekai, '50'),
  'editorBracketPairGuide.activeBackground2': alpha(teals.classic, '50'),
  'editorBracketPairGuide.activeBackground3': alpha(cyans.ice, '50'),
  'editorBracketPairGuide.activeBackground4': alpha(hologram.purple, '50'),
  'editorBracketPairGuide.activeBackground5': alpha(teals.neon, '50'),
  'editorBracketPairGuide.activeBackground6': alpha(pinks.soft, '50'),
  'editorGutter.addedBackground': alpha(character.negi.stalk, '80'),
  'editorGutter.modifiedBackground': alpha(semantic.warning, '80'),
  'editorGutter.deletedBackground': alpha(character.headphones.cushion, '80'),
  'editorGutter.foldingControlForeground': alpha(teals.neon, 'BB'),
  'editorWidget.background': character.boots.base,
  'editorWidget.foreground': versionMapping.hover,
  'editorWidget.border': alpha(character.hair.shadow, '80'),
  'editorWidget.resizeBorder': alpha(character.tie.shadow, '80'),
  'editorHoverWidget.background': alpha(blacks.outfit, 'F5'),
  'editorHoverWidget.border': alpha(character.hair.shadow, '70'),
  'editorHoverWidget.foreground': foregrounds.primary,
  'editorHoverWidget.highlightForeground': character.hair.highlight,
  'editorHoverWidget.statusBarBackground': blacks.sleeve,
  'editorUnnecessaryCode.opacity': alpha(blacks.void, '80'),
  'editorGhostText.foreground': alpha(versions.v6ai, 'BB'),
  'editorGhostText.border': alpha(versions.v6ai, '40'),
  'editorGhostText.background': alpha(versions.v6ai, '0A'),
  'editor.linkedEditingBackground': alpha(cyans.ice, '20'),
  'editorOverviewRuler.bracketMatchForeground': alpha(cyans.ice, 'A0'),
  'editorOverviewRuler.wordHighlightForeground': alpha(cyans.ice, '80'),
  'editorOverviewRuler.wordHighlightStrongForeground': alpha(pinks.sekai, '90'),
  'editorOverviewRuler.wordHighlightTextForeground': alpha(cyans.ice, '60'),
  'editorOverviewRuler.findMatchForeground': alpha(pinks.sekai, '90'),
  'editorOverviewRuler.selectionHighlightForeground': alpha(teals.classic, '50'),
  'editorOverviewRuler.infoForeground': semantic.info,
  'editorOverviewRuler.warningForeground': semantic.warning,
  'editorOverviewRuler.errorForeground': semantic.error,
  'editorLink.activeForeground': hologram.cyan,
  'editorCodeLens.foreground': alpha(teals.neon, 'CC'),
  // Activity Bar - Snow Miku 2017 (Twinkle Snow - Starry constellation)
  'activityBar.background': snowMiku.y2017.outfit.dress, // Midnight blue
  'activityBar.foreground': snowMiku.y2017.hair, // Soft starry blue
  'activityBar.activeBorder': snowMiku.y2017.accessories.stars, // Gold stars
  'activityBar.activeBackground': alpha(snowMiku.y2017.outfit.ribbon, '20'), // Celestial blue glow
  'activityBar.inactiveForeground': snowMiku.y2017.outfit.sheer, // Translucent mist
  'activityBar.border': alpha(snowMiku.y2017.outfit.dress, '60'),
  'activityBarBadge.background': snowMiku.y2017.outfit.constellation, // Glowing constellation
  'activityBarBadge.foreground': snowMiku.y2017.outfit.dress,
  'activityBarTop.foreground': snowMiku.y2017.hair,
  'activityBarTop.activeBorder': snowMiku.y2017.accessories.stars,
  'activityBarTop.inactiveForeground': snowMiku.y2017.outfit.sheer,
  // Sidebar - Snow Miku 2019 (Princess - Winter night royalty)
  'sideBar.background': snowMiku.y2019.outfit.corset, // Midnight blue corset
  'sideBar.foreground': snowMiku.y2019.hair, // Soft icy blue
  'sideBar.border': alpha(snowMiku.y2019.outfit.corset, '50'),
  'sideBar.dropBackground': alpha(snowMiku.y2019.eyes, '20'), // Bright blue eyes
  'sideBarSectionHeader.background': snowMiku.y2019.outfit.dress, // Layered dress
  'sideBarSectionHeader.foreground': snowMiku.y2019.hair,
  'sideBarSectionHeader.border': alpha(snowMiku.y2019.eyes, '25'),
  'sideBarTitle.foreground': snowMiku.y2019.hair,
  'sideBarStickyScroll.background': blacks.sleeve,
  'sideBarStickyScroll.border': alpha(snowMiku.y2019.eyes, '20'),
  'sideBarStickyScroll.shadow': alpha(stage.darkness, '50'),
  // Status Bar - Digital Stars 2024 (BUNBUN Cyber Sporty)
  'statusBar.background': digitalStars.y2024.outfit.jacket, // Dark jacket
  'statusBar.foreground': digitalStars.y2024.outfit.glitchCyan, // Neon cyan
  'statusBar.border': alpha(digitalStars.y2024.outfit.jacket, '70'),
  'statusBar.debuggingBackground': digitalStars.y2024.outfit.glitchPurple, // Electric purple
  'statusBar.debuggingForeground': digitalStars.y2024.outfit.inner, // White
  'statusBar.debuggingBorder': digitalStars.y2024.outfit.glitchPurple,
  'statusBar.noFolderBackground': digitalStars.y2024.outfit.jacket,
  'statusBar.noFolderForeground': digitalStars.y2024.outfit.glitchCyan,
  'statusBar.noFolderBorder': alpha(digitalStars.y2024.outfit.jacket, '40'),
  'statusBarItem.remoteBackground': digitalStars.y2024.outfit.accent, // Neon lime
  'statusBarItem.remoteForeground': digitalStars.y2024.outfit.jacket,
  'statusBarItem.remoteHoverBackground': digitalStars.y2024.hair, // Bright cyan
  'statusBarItem.hoverBackground': alpha(digitalStars.y2024.outfit.glitchCyan, '20'),
  'statusBarItem.hoverForeground': digitalStars.y2024.outfit.glitchCyan,
  'statusBarItem.activeBackground': alpha(digitalStars.y2024.outfit.glitchPurple, '40'),
  'statusBarItem.errorBackground': digitalStars.y2024.outfit.speaker, // Speaker red
  'statusBarItem.errorForeground': digitalStars.y2024.outfit.inner,
  'statusBarItem.errorHoverBackground': alpha(digitalStars.y2024.outfit.speaker, 'CC'),
  'statusBarItem.warningBackground': digitalStars.y2024.outfit.accent, // Neon lime
  'statusBarItem.warningForeground': digitalStars.y2024.outfit.jacket,
  'statusBarItem.warningHoverBackground': alpha(digitalStars.y2024.outfit.accent, 'CC'),
  'statusBarItem.prominentBackground': alpha(digitalStars.y2024.outfit.glitchCyan, '25'),
  'statusBarItem.prominentForeground': digitalStars.y2024.outfit.glitchCyan,
  'statusBarItem.prominentHoverBackground': alpha(digitalStars.y2024.outfit.glitchCyan, '40'),
  'statusBarItem.prominentHoverForeground': digitalStars.y2024.outfit.inner,
  'statusBarItem.compactHoverBackground': alpha(digitalStars.y2024.hair, '30'),
  'statusBarItem.focusBorder': alpha(digitalStars.y2024.outfit.glitchCyan, 'DD'),
  // Title Bar - Miku V2 (2007 Original Turquoise)
  'titleBar.activeBackground': mikuV2.hair.base, // Original turquoise
  'titleBar.activeForeground': mikuV2.outfit.top, // Cooler grey
  'titleBar.inactiveBackground': mikuV2.hair.shadow, // Darker turquoise
  'titleBar.inactiveForeground': alpha(mikuV2.outfit.top, '70'),
  'titleBar.border': alpha(mikuV2.hair.highlight, '30'),
  'menubar.selectionForeground': mikuV2.outfit.top,
  'menubar.selectionBackground': alpha(mikuV2.hair.base, '30'),
  'menubar.selectionBorder': alpha(mikuV2.hair.base, '60'),
  // Tabs - Miku Expo 2026 (Candy Pop - Sweet colorful celebration)
  'tab.activeBackground': alpha(mikuExpo.y2026.outfit.top, '10'),
  'tab.activeForeground': mikuExpo.y2026.hair, // Soft cyan
  'tab.activeBorderTop': mikuExpo.y2026.outfit.skirtPink, // Pink accent
  'tab.activeBorder': alpha(mikuExpo.y2026.outfit.skirtGlitter, '40'), // Glitter purple
  'tab.inactiveBackground': blacks.outfit,
  'tab.inactiveForeground': greys.silver,
  'tab.border': blacks.sleeve,
  'tab.hoverBackground': alpha(mikuExpo.y2026.outfit.skirtPink, '15'),
  'tab.hoverForeground': mikuExpo.y2026.outfit.skirtGlitter,
  'tab.hoverBorder': alpha(mikuExpo.y2026.outfit.skirtPink, '40'),
  'tab.unfocusedActiveBackground': blacks.base,
  'tab.unfocusedActiveForeground': mikuExpo.y2026.hair,
  'tab.unfocusedActiveBorderTop': alpha(mikuExpo.y2026.outfit.skirtPink, '80'),
  'tab.unfocusedInactiveBackground': blacks.outfit,
  'tab.unfocusedInactiveForeground': greys.silver,
  'tab.modifiedBorder': mikuExpo.y2026.outfit.skirtGlitter, // Glitter for modified files
  'editorGroupHeader.tabsBackground': blacks.sleeve,
  'editorGroupHeader.tabsBorder': alpha(mikuExpo.y2026.hair, '15'),
  'editorGroupHeader.noTabsBackground': blacks.outfit,
  'editorGroup.border': alpha(character.tie.shadow, '60'),
  'editorGroup.dropBackground': alpha(mikuExpo.y2026.outfit.skirtPink, '40'),
  // Lists - Snow Miku 2023 (Serene Winter - Kimono elegance)
  'list.activeSelectionBackground': alpha(snowMiku.y2023.outfit.kimono, '30'), // Soft lavender
  'list.activeSelectionForeground': stage.spotlight,
  'list.activeSelectionIconForeground': snowMiku.y2023.outfit.sash, // Pink sash
  'list.inactiveSelectionBackground': alpha(snowMiku.y2023.outfit.kimono, '20'),
  'list.inactiveSelectionForeground': foregrounds.primary,
  'list.hoverBackground': alpha(snowMiku.y2023.outfit.sash, '15'), // Pink hover
  'list.hoverForeground': foregrounds.primary,
  'list.focusBackground': alpha(snowMiku.y2023.outfit.sash, '25'),
  'list.focusForeground': snowMiku.y2023.outfit.sash,
  'list.focusOutline': alpha(snowMiku.y2023.hair, 'DD'), // Soft blue outline
  'list.highlightForeground': snowMiku.y2023.outfit.sash,
  'list.errorForeground': boosted.coralGlow,
  'list.warningForeground': semantic.warning,
  'list.invalidItemForeground': boosted.coralGlow,
  'list.deemphasizedForeground': greys.platinum,
  'listFilterWidget.background': blacks.outfit,
  'listFilterWidget.outline': alpha(pinks.sekai, '70'),
  'listFilterWidget.noMatchesOutline': semantic.error,
  'tree.indentGuidesStroke': alpha(pinks.sekai, '40'),
  'tree.tableColumnsBorder': alpha(pinks.sekai, '25'),
  'focusBorder': lawson50thMiku.hair.highlight, // Lawson 50th cyan blue
  'foreground': foregrounds.primary,
  'disabledForeground': greys.silver,
  'widget.shadow': alpha(stage.darkness, '70'),
  'selection.background': alpha(versionMapping.identity, '40'),
  'descriptionForeground': greys.silver,
  'errorForeground': boosted.coralGlow,
  'icon.foreground': append.light,
  'sash.hoverBorder': alpha(pinks.sekai, '80'),
  // Input - Snow Miku 2026 (Pâtisserie - Sweet pastry theme)
  'input.background': snowMiku.y2026.outfit.apron, // Cream apron
  'input.foreground': snowMiku.y2026.outfit.boots, // Brown boots
  'input.border': alpha(snowMiku.y2026.outfit.ribbon, '50'), // Pink ribbon
  'input.placeholderForeground': snowMiku.y2026.outfit.dress, // Soft pink
  'inputOption.activeBorder': snowMiku.y2026.outfit.ribbon,
  'inputOption.activeBackground': alpha(snowMiku.y2026.outfit.ribbon, '30'),
  'inputOption.activeForeground': snowMiku.y2026.outfit.boots,
  'inputOption.hoverBackground': alpha(snowMiku.y2026.hair, '20'),
  'inputValidation.errorBackground': alpha(semantic.error, '25'),
  'inputValidation.errorBorder': semantic.error,
  'inputValidation.errorForeground': boosted.coralGlow,
  'inputValidation.warningBackground': alpha(semantic.warning, '25'),
  'inputValidation.warningBorder': semantic.warning,
  'inputValidation.warningForeground': semantic.warning,
  'inputValidation.infoBackground': alpha(semantic.info, '25'),
  'inputValidation.infoBorder': semantic.info,
  'inputValidation.infoForeground': semantic.info,
  // Dropdown - Miku Expo 2020 Europe
  'dropdown.background': mikuExpo.y2020.europe.outfit.top, // Deep blue
  'dropdown.foreground': mikuExpo.y2020.europe.hair, // Cyan
  'dropdown.border': alpha(mikuExpo.y2020.europe.hair, '50'),
  'dropdown.listBackground': mikuExpo.y2020.europe.outfit.top,
  // Buttons - Magical Mirai 2018 (Mika Pikazo)
  'button.background': magicalMirai.y2018.outfit.skirtLayer, // Bright green
  'button.foreground': magicalMirai.y2018.outfit.bootNavy, // Dark navy
  'button.hoverBackground': magicalMirai.y2018.hair, // Neon cyan
  'button.secondaryBackground': magicalMirai.y2018.outfit.top, // White top
  'button.secondaryForeground': magicalMirai.y2018.outfit.bootNavy,
  'button.secondaryHoverBackground': magicalMirai.y2018.outfit.skirtFrills, // White frills
  'button.border': alpha(magicalMirai.y2018.outfit.skirtLayer, '80'),
  'checkbox.background': blacks.sleeve,
  'checkbox.foreground': teals.classic,
  'checkbox.border': alpha(character.tie.shadow, '50'),
  // Scrollbar - Snow Miku 2018 (Crane - Red obi & gold bell)
  'scrollbar.shadow': alpha(stage.darkness, '50'),
  'scrollbarSlider.background': alpha(snowMiku.y2018.outfit.obi, '40'), // Red obi
  'scrollbarSlider.hoverBackground': alpha(snowMiku.y2018.accessories.bell, '60'), // Gold bell
  'scrollbarSlider.activeBackground': alpha(snowMiku.y2018.outfit.obi, '80'),
  // Minimap - Snow Miku 2016 (Owl - Amber goggles & cyan)
  'minimap.findMatchHighlight': alpha(snowMiku.y2016.accessories.goggles, '90'), // Amber goggles
  'minimap.selectionHighlight': alpha(snowMiku.y2016.hair, '70'), // Cyan hair
  'minimap.errorHighlight': alpha(boosted.coralGlow, '95'),
  'minimap.warningHighlight': alpha(snowMiku.y2016.accessories.goggles, '90'),
  'minimap.background': alpha(character.armDisplay.screen, '08'),
  'minimap.selectionOccurrenceHighlight': alpha(snowMiku.y2016.hair, '50'),
  'minimap.foregroundOpacity': alpha(stage.darkness, 'BB'),
  'minimap.infoHighlight': alpha(snowMiku.y2016.hair, '80'),
  'minimapSlider.background': alpha(snowMiku.y2016.outfit.jacket, '20'), // White jacket
  'minimapSlider.hoverBackground': alpha(snowMiku.y2016.accessories.goggles, '40'),
  'minimapSlider.activeBackground': alpha(snowMiku.y2016.accessories.goggles, '45'),
  'minimapGutter.addedBackground': alpha(snowMiku.y2015.outfit.leafTrim, '90'), // Green trim from 2015
  'minimapGutter.modifiedBackground': alpha(snowMiku.y2016.accessories.goggles, '90'),
  'minimapGutter.deletedBackground': alpha(boosted.coralGlow, '90'),
  // Breadcrumbs - Snow Miku 2015 (Bell - Fresh green & cyan)
  'breadcrumb.foreground': snowMiku.y2015.outfit.leafTrim, // Fresh green
  'breadcrumb.background': blacks.base,
  'breadcrumb.focusForeground': snowMiku.y2015.hair, // Cyan
  'breadcrumb.activeSelectionForeground': snowMiku.y2015.hair,
  'breadcrumbPicker.background': blacks.outfit,
  'terminal.background': character.skirt.base,
  'terminal.foreground': foregrounds.primary,
  'terminal.ansiBlack': blacks.base,
  'terminal.ansiRed': boosted.coralGlow,
  'terminal.ansiGreen': character.negi.stalk,
  'terminal.ansiYellow': iconicPVs.worldIsMine.crown,
  'terminal.ansiBlue': hologram.cyan,
  'terminal.ansiMagenta': iconicPVs.melt.blush,
  'terminal.ansiCyan': character.hair.highlight,
  'terminal.ansiWhite': greys.platinum,
  'terminal.ansiBrightBlack': greys.silver,
  'terminal.ansiBrightRed': seasonalExpanded.valentine.heartRed,
  'terminal.ansiBrightGreen': racingMiku.y2014.limeAccent,
  'terminal.ansiBrightYellow': mikuDay.celebration.confettiYellow,
  'terminal.ansiBrightBlue': cyans.ice,
  'terminal.ansiBrightMagenta': pinks.blush,
  'terminal.ansiBrightCyan': racingMiku.y2017.highlightCyan,
  'terminal.ansiBrightWhite': stage.spotlight,
  'terminal.selectionBackground': alpha(teals.classic, '40'),
  'terminal.inactiveSelectionBackground': alpha(teals.classic, '25'),
  'terminal.findMatchBackground': alpha(pinks.sekai, '50'),
  'terminal.findMatchBorder': alpha(pinks.sekai, '90'),
  'terminal.findMatchHighlightBackground': alpha(accents.gold, '30'),
  'terminal.findMatchHighlightBorder': alpha(accents.gold, '60'),
  'terminalCursor.foreground': character.hairTies.base,
  'terminalCursor.background': character.skirt.base,
  'terminal.border': alpha(character.tie.shadow, '60'),
  'terminal.tab.activeBorder': pinks.sekai,
  'terminalCommandDecoration.defaultBackground': alpha(teals.classic, '60'),
  'terminalCommandDecoration.successBackground': alpha(racingMiku.team.gsmTeal, '90'),
  'terminalCommandDecoration.errorBackground': alpha(semantic.error, '90'),
  'terminalOverviewRuler.cursorForeground': pinks.sekai,
  'terminalOverviewRuler.findMatchForeground': alpha(pinks.sekai, '80'),
  'textLink.foreground': hologram.cyan,
  'textLink.activeForeground': cyans.ice,
  'textBlockQuote.background': blacks.outfit,
  'textBlockQuote.border': alpha(teals.classic, '60'),
  'textCodeBlock.background': blacks.sleeve,
  'textPreformat.foreground': semantic.success,
  'textSeparator.foreground': alpha(teals.classic, '30'),
  'notifications.background': alpha(blacks.outfit, 'F5'),
  'notifications.foreground': foregrounds.primary,
  'notifications.border': alpha(character.tie.shadow, '70'),
  'notificationToast.border': alpha(character.tie.shadow, '80'),
  'notificationsInfoIcon.foreground': pinks.blush,
  'notificationsWarningIcon.foreground': accents.amber,
  'notificationsErrorIcon.foreground': boosted.coralGlow,
  'notificationLink.foreground': versions.v6ai,
  'notificationCenterHeader.background': alpha(blacks.sleeve, 'F0'),
  'notificationCenterHeader.foreground': append.vivid,
  'notificationCenter.border': alpha(character.tie.shadow, '60'),
  'peekView.border': alpha(character.tie.shadow, '90'),
  'peekViewEditor.background': character.skirt.base,
  'peekViewEditorGutter.background': character.headphones.frame,
  'peekViewResult.background': character.headphones.frame,
  'peekViewResult.selectionBackground': alpha(teals.classic, '30'),
  'peekViewResult.selectionForeground': stage.spotlight,
  'peekViewTitle.background': blacks.void,
  'peekViewTitleLabel.foreground': teals.bright,
  'peekViewTitleDescription.foreground': greys.platinum,
  'peekViewResult.fileForeground': foregrounds.primary,
  'peekViewResult.lineForeground': append.light,
  'peekViewResult.matchHighlightBackground': alpha(pinks.sekai, '50'),
  'peekViewEditor.matchHighlightBackground': alpha(pinks.sekai, '50'),
  'peekViewEditor.matchHighlightBorder': alpha(pinks.sekai, '80'),
  'pickerGroup.border': alpha(teals.classic, '30'),
  'pickerGroup.foreground': teals.classic,
  'gitDecoration.addedResourceForeground': character.negi.bright,
  'gitDecoration.modifiedResourceForeground': character.hair.highlight,
  'gitDecoration.deletedResourceForeground': boosted.coralGlow,
  'gitDecoration.renamedResourceForeground': hologram.cyan,
  'gitDecoration.untrackedResourceForeground': character.hair.highlight,
  'gitDecoration.ignoredResourceForeground': greys.silver,
  'gitDecoration.conflictingResourceForeground': accents.orange,
  'gitDecoration.stageModifiedResourceForeground': accents.gold,
  'gitDecoration.stageDeletedResourceForeground': pinks.blush,
  'gitDecoration.submoduleResourceForeground': semantic.info,
  'diffEditor.insertedTextBackground': alpha(character.negi.bright, '30'),
  'diffEditor.removedTextBackground': alpha(character.headphones.cushion, '30'),
  'diffEditor.insertedLineBackground': alpha(character.negi.white, '20'),
  'diffEditor.removedLineBackground': alpha(character.headphones.cushion, '18'),
  'diffEditor.diagonalFill': alpha(teals.classic, '15'),
  'diffEditor.border': alpha(character.tie.shadow, '60'),
  'diffEditor.unchangedRegionBackground': blacks.outfit,
  'diffEditor.unchangedRegionForeground': greys.silver,
  'diffEditor.unchangedCodeBackground': alpha(teals.classic, '08'),
  'diffEditorGutter.insertedLineBackground': alpha(character.negi.stalk, '50'),
  'diffEditorGutter.removedLineBackground': alpha(character.headphones.cushion, '40'),
  'diffEditorOverview.insertedForeground': semantic.success,
  'diffEditorOverview.removedForeground': semantic.error,
  'multiDiffEditor.headerBackground': blacks.outfit,
  'multiDiffEditor.background': blacks.void,
  'multiDiffEditor.border': alpha(teals.classic, '30'),
  'panel.background': blacks.void,
  'panel.border': alpha(character.tie.shadow, '70'),
  'panel.dropBorder': alpha(character.hair.highlight, 'DD'),
  'panelTitle.activeForeground': teals.classic,
  'panelTitle.inactiveForeground': greys.silver,
  'panelTitle.activeBorder': pinks.sekai,
  'panelInput.border': alpha(teals.classic, '40'),
  'panelSection.border': alpha(pinks.sekai, '35'),
  'panelSection.dropBackground': alpha(pinks.sekai, '25'),
  'panelSectionHeader.background': character.top.main,
  'panelSectionHeader.foreground': character.hair.highlight,
  'panelSectionHeader.border': alpha(character.tie.base, '20'),
  'debugToolBar.background': alpha(stage.ambientTeal, '20'),
  'debugToolBar.border': alpha(stage.accentPink, '60'),
  'debugIcon.breakpointForeground': pinks.sekai,
  'debugIcon.breakpointDisabledForeground': alpha(pinks.sekai, '50'),
  'debugIcon.breakpointUnverifiedForeground': semantic.warning,
  'debugIcon.breakpointCurrentStackframeForeground': cyans.ice,
  'debugIcon.breakpointStackframeForeground': semantic.success,
  'debugIcon.startForeground': semantic.success,
  'debugIcon.pauseForeground': semantic.warning,
  'debugIcon.stopForeground': semantic.error,
  'debugIcon.disconnectForeground': semantic.error,
  'debugIcon.restartForeground': semantic.success,
  'debugIcon.stepOverForeground': semantic.info,
  'debugIcon.stepIntoForeground': semantic.info,
  'debugIcon.stepOutForeground': semantic.info,
  'debugIcon.stepBackForeground': semantic.info,
  'debugIcon.continueForeground': semantic.success,
  'debugConsole.infoForeground': hologram.cyan,
  'debugConsole.warningForeground': stage.warmAmber,
  'debugConsole.errorForeground': boosted.coralGlow,
  'debugConsole.sourceForeground': semantic.success,
  'debugConsoleInputIcon.foreground': teals.classic,
  'debugTokenExpression.name': character.hair.highlight,
  'debugTokenExpression.value': foregrounds.primary,
  'debugTokenExpression.string': character.negi.stalk,
  'debugTokenExpression.number': character.negi.bright,
  'debugTokenExpression.boolean': pinks.blush,
  'debugTokenExpression.error': boosted.coralGlow,
  'debugView.exceptionLabelForeground': stage.spotlight,
  'debugView.exceptionLabelBackground': semantic.error,
  'debugView.stateLabelForeground': foregrounds.primary,
  'debugView.stateLabelBackground': alpha(teals.classic, '40'),
  'debugView.valueChangedHighlight': alpha(semantic.warning, '80'),
  'editor.stackFrameHighlightBackground': alpha(pinks.sekai, '25'),
  'editor.focusedStackFrameHighlightBackground': alpha(cyans.ice, '20'),
  'testing.iconFailed': projectDiva.ratings.sad,
  'testing.iconErrored': projectDiva.ratings.worst,
  'testing.iconPassed': racingMiku.y2014.limeAccent,
  'testing.iconQueued': projectDiva.ratings.good,
  'testing.iconUnset': projectDiva.ratings.safe,
  'testing.iconSkipped': derivativeCharacters.grayMiku.hairMid,
  'testing.runAction': projectDiva.ratings.perfect,
  'testing.peekBorder': teals.classic,
  'testing.peekHeaderBackground': blacks.outfit,
  'testing.message.error.decorationForeground': boosted.coralGlow,
  'testing.message.error.lineBackground': alpha(semantic.error, '15'),
  'testing.message.info.decorationForeground': semantic.info,
  'testing.message.info.lineBackground': alpha(semantic.info, '15'),
  'mergeEditor.change.background': alpha(semantic.warning, '15'),
  'mergeEditor.change.word.background': alpha(semantic.warning, '30'),
  'mergeEditor.conflict.handled.minimapOverViewRuler': semantic.success,
  'mergeEditor.conflict.handledFocused.border': semantic.success,
  'mergeEditor.conflict.handledUnfocused.border': alpha(semantic.success, '80'),
  'mergeEditor.conflict.unhandled.minimapOverViewRuler': semantic.error,
  'mergeEditor.conflict.unhandledFocused.border': semantic.error,
  'mergeEditor.conflict.unhandledUnfocused.border': alpha(semantic.error, '80'),
  'mergeEditor.conflictingLines.background': alpha(semantic.error, '15'),
  'settings.headerForeground': character.hair.highlight,
  'settings.modifiedItemIndicator': pinks.sekai,
  'settings.focusedRowBackground': alpha(versionMapping.focus, '10'),
  'settings.rowHoverBackground': alpha(versionMapping.hover, '08'),
  'settings.focusedRowBorder': alpha(versionMapping.focus, '40'),
  'settings.headerBorder': alpha(teals.classic, '20'),
  'settings.sashBorder': alpha(teals.classic, '30'),
  'settings.dropdownBackground': blacks.sleeve,
  'settings.dropdownForeground': foregrounds.primary,
  'settings.dropdownBorder': alpha(teals.classic, '40'),
  'settings.dropdownListBorder': alpha(teals.classic, '40'),
  'settings.checkboxBackground': blacks.sleeve,
  'settings.checkboxForeground': teals.classic,
  'settings.checkboxBorder': alpha(teals.classic, '40'),
  'settings.textInputBackground': blacks.sleeve,
  'settings.textInputForeground': foregrounds.primary,
  'settings.textInputBorder': alpha(teals.classic, '40'),
  'settings.numberInputBackground': blacks.sleeve,
  'settings.numberInputForeground': foregrounds.primary,
  'settings.numberInputBorder': alpha(teals.classic, '40'),
  'welcomePage.background': blacks.base,
  'welcomePage.tileBackground': blacks.outfit,
  'welcomePage.tileBorder': alpha(teals.classic, '30'),
  'welcomePage.tileHoverBackground': alpha(versionMapping.hover, '10'),
  'welcomePage.progress.foreground': character.hair.highlight,
  'welcomePage.progress.background': blacks.sleeve,
  'walkThrough.embeddedEditorBackground': blacks.outfit,
  'extensionButton.prominentBackground': teals.classic,
  'extensionButton.prominentForeground': blacks.void,
  'extensionButton.prominentHoverBackground': teals.stage,
  'extensionButton.separator': blacks.void,
  'extensionBadge.remoteBackground': pinks.sekai,
  'extensionBadge.remoteForeground': blacks.void,
  'extensionIcon.starForeground': semantic.warning,
  'extensionIcon.verifiedForeground': semantic.success,
  'extensionIcon.preReleaseForeground': semantic.warning,
  'extensionIcon.sponsorForeground': pinks.sekai,
  'keybindingLabel.background': alpha(teals.classic, '20'),
  'keybindingLabel.foreground': character.hair.highlight,
  'keybindingLabel.border': alpha(teals.classic, '40'),
  'keybindingLabel.bottomBorder': alpha(teals.classic, '60'),
  'keybindingTable.headerBackground': blacks.sleeve,
  'keybindingTable.rowsBackground': blacks.outfit,
  'charts.foreground': foregrounds.primary,
  'charts.lines': alpha(teals.classic, '60'),
  'charts.red': semantic.error,
  'charts.green': semantic.success,
  'charts.yellow': semantic.warning,
  'charts.blue': semantic.info,
  'charts.purple': hologram.purple,
  'charts.orange': accents.orange,
  'menu.background': blacks.outfit,
  'menu.foreground': foregrounds.primary,
  'menu.selectionBackground': alpha(teals.classic, '30'),
  'menu.selectionForeground': stage.spotlight,
  'menu.selectionBorder': alpha(teals.classic, '50'),
  'menu.separatorBackground': alpha(teals.classic, '30'),
  'menu.border': alpha(character.tie.shadow, '60'),
  'commandCenter.foreground': foregrounds.primary,
  'commandCenter.background': blacks.sleeve,
  'commandCenter.border': alpha(character.tie.shadow, '50'),
  'commandCenter.activeBackground': alpha(teals.classic, '25'),
  'commandCenter.activeForeground': teals.classic,
  'commandCenter.activeBorder': alpha(teals.classic, '60'),
  'commandCenter.inactiveForeground': greys.silver,
  'commandCenter.inactiveBorder': alpha(teals.classic, '20'),
  'quickInput.background': character.boots.base,
  'quickInput.foreground': foregrounds.primary,
  'quickInputTitle.background': character.armWarmers.base,
  'quickInputList.focusBackground': alpha(versionMapping.focus, '30'),
  'quickInputList.focusForeground': stage.spotlight,
  'quickInputList.focusIconForeground': pinks.blush,
  'banner.background': blacks.outfit,
  'banner.foreground': foregrounds.primary,
  'banner.iconForeground': teals.classic,
  'editorError.foreground': boosted.coralGlow,
  'editorError.border': alpha(boosted.coralGlow, '40'),
  'editorError.background': alpha(boosted.coralGlow, '15'),
  'editorWarning.foreground': semantic.warning,
  'editorWarning.border': alpha(semantic.warning, '40'),
  'editorWarning.background': alpha(semantic.warning, '15'),
  'editorInfo.foreground': semantic.info,
  'editorInfo.border': alpha(semantic.info, '40'),
  'editorInfo.background': alpha(semantic.info, '15'),
  'editorHint.foreground': semantic.success,
  'editorHint.border': alpha(semantic.success, '40'),
  'problemsErrorIcon.foreground': boosted.coralGlow,
  'problemsWarningIcon.foreground': semantic.warning,
  'problemsInfoIcon.foreground': semantic.info,
  'editorLightBulb.foreground': versions.nt,
  'editorLightBulbAutoFix.foreground': semantic.success,
  'editorLightBulbAi.foreground': versions.v6ai,
  'editorInlayHint.background': alpha(cyans.ice, '12'),
  'editorInlayHint.foreground': alpha(teals.neon, 'DD'),
  'editorInlayHint.typeForeground': alpha(versionMapping.types, 'CC'),
  'editorInlayHint.typeBackground': alpha(versionMapping.types, '12'),
  'editorInlayHint.parameterForeground': pinks.blush,
  'editorInlayHint.parameterBackground': alpha(pinks.soft, '12'),
  'editorStickyScroll.background': alpha(blacks.outfit, 'F0'),
  'editorStickyScroll.border': alpha(cyans.ice, '30'),
  'editorStickyScrollHover.background': alpha(versionMapping.hover, '10'),
  'notebook.cellBorderColor': alpha(teals.classic, '30'),
  'notebook.cellEditorBackground': blacks.outfit,
  'notebook.cellHoverBackground': alpha(versionMapping.hover, '10'),
  'notebook.cellInsertionIndicator': cyans.ice,
  'notebook.cellStatusBarItemHoverBackground': alpha(versionMapping.hover, '20'),
  'notebook.cellToolbarSeparator': alpha(teals.classic, '30'),
  'notebook.editorBackground': blacks.base,
  'notebook.focusedCellBorder': character.hair.highlight,
  'notebook.focusedEditorBorder': alpha(character.hair.highlight, 'CC'),
  'notebook.inactiveFocusedCellBorder': alpha(teals.classic, '60'),
  'notebook.outputContainerBackgroundColor': blacks.outfit,
  'notebook.outputContainerBorderColor': alpha(teals.classic, '20'),
  'notebook.selectedCellBackground': alpha(teals.classic, '15'),
  'notebook.selectedCellBorder': alpha(teals.classic, '60'),
  'notebook.symbolHighlightBackground': alpha(teals.classic, '20'),
  'notebookStatusSuccessIcon.foreground': semantic.success,
  'notebookStatusErrorIcon.foreground': semantic.error,
  'notebookStatusRunningIcon.foreground': semantic.warning,
  'notebookEditorOverviewRuler.runningCellForeground': semantic.warning,
  'symbolIcon.arrayForeground': teals.stage,
  'symbolIcon.booleanForeground': character.hairTies.outline,
  'symbolIcon.classForeground': accents.amber,
  'symbolIcon.colorForeground': pinks.sekai,
  'symbolIcon.constantForeground': character.negi.bright,
  'symbolIcon.constructorForeground': accents.orange,
  'symbolIcon.enumeratorForeground': boosted.purple,
  'symbolIcon.enumeratorMemberForeground': character.negi.stalk,
  'symbolIcon.eventForeground': accents.gold,
  'symbolIcon.fieldForeground': character.skin.shadow,
  'symbolIcon.fileForeground': foregrounds.primary,
  'symbolIcon.folderForeground': teals.classic,
  'symbolIcon.functionForeground': hologram.cyan,
  'symbolIcon.interfaceForeground': hologram.cyan,
  'symbolIcon.keyForeground': character.hair.highlight,
  'symbolIcon.keywordForeground': character.hair.highlight,
  'symbolIcon.methodForeground': character.negi.stalk,
  'symbolIcon.moduleForeground': foregrounds.primary,
  'symbolIcon.namespaceForeground': hologram.cyan,
  'symbolIcon.nullForeground': character.hair.highlight,
  'symbolIcon.numberForeground': character.negi.bright,
  'symbolIcon.objectForeground': foregrounds.primary,
  'symbolIcon.operatorForeground': accents.orange,
  'symbolIcon.packageForeground': append.light,
  'symbolIcon.propertyForeground': character.skin.blush,
  'symbolIcon.referenceForeground': teals.stage,
  'symbolIcon.snippetForeground': character.negi.stalk,
  'symbolIcon.stringForeground': character.negi.stalk,
  'symbolIcon.structForeground': pinks.blush,
  'symbolIcon.textForeground': foregrounds.primary,
  'symbolIcon.typeParameterForeground': boosted.purple,
  'symbolIcon.unitForeground': pinks.sekai,
  'symbolIcon.variableForeground': foregrounds.primary,
  'inlineChat.background': alpha(blacks.outfit, 'F8'),
  'inlineChat.border': alpha(hologram.purple, '60'),
  'inlineChat.shadow': alpha(hologram.purple, '40'),
  'inlineChatInput.background': blacks.sleeve,
  'inlineChatInput.border': alpha(hologram.purple, '40'),
  'inlineChatInput.focusBorder': hologram.purple,
  'inlineChatInput.placeholderForeground': greys.silver,
  'inlineChatDiff.inserted': alpha(hologram.purple, '25'),
  'inlineChatDiff.removed': alpha(artStyles.lam.shockPink, '20'),
  'chat.requestBackground': blacks.outfit,
  'chat.requestBorder': alpha(teals.classic, '30'),
  'ports.iconRunningProcessForeground': semantic.success,
  'profileBadge.background': teals.classic,
  'profileBadge.foreground': foregrounds.bright,
  'searchEditor.findMatchBackground': alpha(pinks.sekai, '30'),
  'searchEditor.findMatchBorder': alpha(pinks.sekai, '80'),
  'searchEditor.textInputBorder': alpha(teals.classic, '40'),
  'editorUnicodeHighlight.border': alpha(semantic.warning, '80'),
  'editorUnicodeHighlight.background': alpha(semantic.warning, '15'),
  'editorSuggestWidget.background': alpha(blacks.sleeve, 'F8'),
  'editorSuggestWidget.border': alpha(artStyles.ixima.techCyan, 'CC'),
  'editorSuggestWidget.foreground': foregrounds.primary,
  'editorSuggestWidget.highlightForeground': character.skin.highlight,
  'editorSuggestWidget.selectedBackground': alpha(hologram.purple, '30'),
  'editorSuggestWidget.selectedForeground': stage.spotlight,
  'editorSuggestWidget.selectedIconForeground': hologram.purple,
  'editorSuggestWidget.focusHighlightForeground': artStyles.mikaPikazo.triadicCyan,
  'editorMarkerNavigation.background': numberSymbolism.tattoo01.background,
  'editorMarkerNavigationError.background': alpha(digital.glitch, '30'),
  'editorMarkerNavigationWarning.background': alpha(semantic.warning, '30'),
  'editorMarkerNavigationInfo.background': alpha(numberSymbolism.tattoo01.glow, '30'),
  'editorMarkerNavigationError.headerBackground': alpha(semantic.error, '20'),
  'editorMarkerNavigationWarning.headerBackground': alpha(semantic.warning, '20'),
  'editorMarkerNavigationInfo.headerBackground': alpha(semantic.info, '20'),
  'actionBar.toggledBackground': alpha(teals.classic, '30'),
  'toolbar.hoverBackground': alpha(versionMapping.hover, '20'),
  'toolbar.hoverOutline': alpha(versionMapping.hover, '40'),
  'toolbar.activeBackground': alpha(v4xVoice.hard, '30'),
  'editorActionList.background': blacks.outfit,
  'editorActionList.foreground': foregrounds.primary,
  'editorActionList.focusBackground': alpha(versionMapping.focus, '30'),
  'editorActionList.focusForeground': stage.spotlight,
  'editorCommentsWidget.resolvedBorder': alpha(semantic.success, '60'),
  'editorCommentsWidget.unresolvedBorder': alpha(semantic.warning, '60'),
  'editorCommentsWidget.rangeBackground': alpha(teals.classic, '10'),
  'editorCommentsWidget.rangeActiveBackground': alpha(teals.classic, '20'),
  'editorCommentsWidget.replyInputBackground': blacks.sleeve,
  'editor.foldBackground': alpha(cyans.ice, '08'),
  'editor.foldPlaceholderForeground': alpha(teals.neon, 'AA'),
  'editor.snippetTabstopHighlightBackground': alpha(cyans.ice, '18'),
  'editor.snippetTabstopHighlightBorder': alpha(cyans.ice, '50'),
  'editor.snippetFinalTabstopHighlightBackground': alpha(pinks.sekai, '20'),
  'editor.snippetFinalTabstopHighlightBorder': alpha(pinks.sekai, '60'),
  'editor.symbolHighlightBackground': alpha(cyans.ice, '15'),
  'editor.symbolHighlightBorder': alpha(cyans.ice, '40'),
  'editor.hoverHighlightBackground': alpha(cyans.ice, '12'),
  'scmGraph.foreground1': teals.classic,
  'scmGraph.foreground2': pinks.sekai,
  'scmGraph.foreground3': hologram.purple,
  'scmGraph.foreground4': semantic.info,
  'scmGraph.foreground5': semantic.warning,
  'chat.slashCommandBackground': alpha(hologram.purple, '20'),
  'chat.slashCommandForeground': hologram.purple,
  'chat.avatarBackground': alpha(hologram.purple, '30'),
  'chat.avatarForeground': hologram.purple,
  'interactive.activeCodeBorder': alpha(versions.v6ai, '60'),
  'interactive.inactiveCodeBorder': alpha(teals.classic, '30'),
  'terminalSymbolIcon.aliasForeground': append.light,
  'terminalSymbolIcon.branchForeground': character.hair.highlight,
  'terminalSymbolIcon.commitForeground': hologram.cyan,
  'terminalSymbolIcon.flagForeground': accents.amber,
  'terminalSymbolIcon.optionForeground': foregrounds.primary,
  'terminalSymbolIcon.optionValueForeground': character.negi.stalk,
  'terminalSymbolIcon.methodForeground': character.skin.blush,
  'terminalSymbolIcon.argumentForeground': append.light,
  'terminalSymbolIcon.inlineSuggestionForeground': versions.v6ai,
  'terminalSymbolIcon.fileForeground': foregrounds.primary,
  'terminalSymbolIcon.folderForeground': teals.classic,
  'terminalSymbolIcon.pullRequestDoneForeground': semantic.success,
  'terminalSymbolIcon.pullRequestForeground': pinks.soft,
  'terminalSymbolIcon.remoteForeground': hologram.cyan,
  'terminalSymbolIcon.stashForeground': greys.slate,
  'terminalSymbolIcon.symbolText': foregrounds.primary,
  'terminalSymbolIcon.symbolicLinkFileForeground': hologram.purple,
  'terminalSymbolIcon.symbolicLinkFolderForeground': boosted.purple,
  'terminalSymbolIcon.tagForeground': accents.gold,
  'inlineEdit.gutterIndicator.primaryBorder': versions.v6ai,
  'inlineEdit.gutterIndicator.primaryForeground': versions.v6ai,
  'inlineEdit.gutterIndicator.primaryBackground': alpha(versions.v6ai, '20'),
  'inlineEdit.gutterIndicator.secondaryBorder': alpha(teals.classic, '60'),
  'inlineEdit.gutterIndicator.secondaryForeground': character.hair.highlight,
  'inlineEdit.gutterIndicator.secondaryBackground': alpha(teals.classic, '15'),
  'inlineEdit.gutterIndicator.successfulBorder': character.negi.bright,
  'inlineEdit.gutterIndicator.successfulForeground': character.negi.bright,
  'inlineEdit.gutterIndicator.successfulBackground': alpha(character.negi.bright, '20'),
  'inlineEdit.gutterIndicator.background': alpha(versions.v6ai, '10'),
  'inlineEdit.originalBackground': alpha(greys.slate, '10'),
  'inlineEdit.modifiedBackground': alpha(hologram.cyan, '15'),
  'inlineEdit.originalChangedLineBackground': alpha(greys.slate, '15'),
  'inlineEdit.originalChangedTextBackground': alpha(greys.slate, '25'),
  'inlineEdit.modifiedChangedLineBackground': alpha(versions.v6ai, '15'),
  'inlineEdit.modifiedChangedTextBackground': alpha(versions.v6ai, '25'),
  'inlineEdit.originalBorder': alpha(greys.slate, '40'),
  'inlineEdit.modifiedBorder': alpha(versions.v6ai, '50'),
  'inlineEdit.tabWillAcceptModifiedBorder': character.negi.bright,
  'inlineEdit.tabWillAcceptOriginalBorder': alpha(greys.slate, '60'),
  'testing.iconErrored.retired': alpha(semantic.error, '60'),
  'testing.iconFailed.retired': alpha(semantic.error, '60'),
  'testing.iconPassed.retired': alpha(semantic.success, '60'),
  'testing.iconQueued.retired': alpha(semantic.warning, '60'),
  'testing.iconUnset.retired': alpha(greys.slate, '60'),
  'testing.iconSkipped.retired': alpha(greys.slate, '60'),
  'testing.message.error.badgeBackground': alpha(semantic.error, '25'),
  'testing.message.error.badgeBorder': semantic.error,
  'testing.message.error.badgeForeground': boosted.coralGlow,
  'testing.messagePeekBorder': teals.classic,
  'testing.messagePeekHeaderBackground': blacks.outfit,
  'testing.coveredBackground': alpha(character.negi.bright, '12'),
  'testing.coveredBorder': alpha(character.negi.bright, '40'),
  'testing.coveredGutterBackground': alpha(character.negi.bright, '30'),
  'testing.uncoveredBranchBackground': alpha(accents.coral, '20'),
  'testing.uncoveredBackground': alpha(accents.coral, '12'),
  'testing.uncoveredBorder': alpha(accents.coral, '40'),
  'testing.uncoveredGutterBackground': alpha(accents.coral, '30'),
  'testing.coverCountBadgeBackground': alpha(teals.classic, '25'),
  'testing.coverCountBadgeForeground': character.hair.highlight,
  'scmGraph.historyItemHoverAdditionsForeground': semantic.success,
  'scmGraph.historyItemHoverDeletionsForeground': boosted.coralGlow,
  'scmGraph.historyItemRefColor': character.hair.highlight,
  'scmGraph.historyItemRemoteRefColor': pinks.soft,
  'scmGraph.historyItemBaseRefColor': teals.classic,
  'chat.editedFileForeground': hologram.cyan,
  'chat.linesAddedForeground': character.negi.bright,
  'chat.linesRemovedForeground': boosted.coralGlow,
  'chat.requestCodeBorder': alpha(versions.v6ai, '40'),
  'chat.requestBubbleBackground': alpha(teals.classic, '15'),
  'chat.requestBubbleHoverBackground': alpha(teals.classic, '25'),
  'chat.checkpointSeparator': alpha(teals.classic, '30'),
  'chatManagement.sashBorder': alpha(versions.v6ai, '40'),
  'tab.lastPinnedBorder': alpha(pinks.sekai, '60'),
  'tab.activeModifiedBorder': pinks.hot,
  'tab.inactiveModifiedBorder': alpha(pinks.hot, '60'),
  'tab.unfocusedActiveModifiedBorder': alpha(pinks.hot, '80'),
  'tab.unfocusedInactiveModifiedBorder': alpha(pinks.hot, '40'),
  'tab.dragAndDropBorder': alpha(teals.classic, '60'),
  'tab.selectedBackground': blacks.base,
  'tab.selectedForeground': character.hair.highlight,
  'tab.selectedBorderTop': teals.classic,
  'checkbox.selectBackground': alpha(teals.classic, '30'),
  'checkbox.selectBorder': teals.classic,
  'checkbox.disabled.background': alpha(greys.slate, '20'),
  'checkbox.disabled.foreground': greys.silver,
  'radio.activeForeground': foregrounds.bright,
  'radio.activeBackground': teals.classic,
  'radio.activeBorder': teals.neon,
  'radio.inactiveForeground': greys.silver,
  'radio.inactiveBackground': blacks.sleeve,
  'radio.inactiveBorder': alpha(teals.classic, '40'),
  'radio.inactiveHoverBackground': alpha(teals.classic, '15'),
  'editorOverviewRuler.modifiedForeground': alpha(semantic.warning, '90'),
  'editorOverviewRuler.addedForeground': alpha(semantic.success, '90'),
  'editorOverviewRuler.deletedForeground': alpha(semantic.error, '90'),
  'editorOverviewRuler.commentForeground': alpha(foregrounds.comment, '60'),
  'editorOverviewRuler.commentUnresolvedForeground': alpha(semantic.warning, '60'),
  'editorOverviewRuler.inlineChatInserted': alpha(versions.v6ai, '70'),
  'editorOverviewRuler.inlineChatRemoved': alpha(pinks.sekai, '70'),
  'editorGutter.modifiedSecondaryBackground': alpha(semantic.warning, '50'),
  'editorGutter.addedSecondaryBackground': alpha(semantic.success, '50'),
  'editorGutter.deletedSecondaryBackground': alpha(semantic.error, '50'),
  'editorGutter.commentRangeForeground': alpha(foregrounds.comment, '40'),
  'editorGutter.commentGlyphForeground': hologram.cyan,
  'editorGutter.commentUnresolvedGlyphForeground': semantic.warning,
  'merge.currentHeaderBackground': alpha(hologram.cyan, '40'),
  'merge.currentContentBackground': alpha(hologram.cyan, '15'),
  'merge.incomingHeaderBackground': alpha(pinks.sekai, '40'),
  'merge.incomingContentBackground': alpha(pinks.sekai, '15'),
  'merge.border': alpha(character.tie.shadow, '70'),
  'merge.commonContentBackground': alpha(greys.slate, '15'),
  'merge.commonHeaderBackground': alpha(greys.slate, '30'),
  'mergeEditor.changeBase.background': alpha(greys.slate, '15'),
  'mergeEditor.changeBase.word.background': alpha(greys.slate, '30'),
  'mergeEditor.conflict.input1.background': alpha(hologram.cyan, '15'),
  'mergeEditor.conflict.input2.background': alpha(pinks.sekai, '15'),
  'panelTitleBadge.background': teals.classic,
  'panelTitleBadge.foreground': stage.spotlight,
  'panelStickyScroll.background': blacks.void,
  'panelStickyScroll.border': alpha(teals.classic, '20'),
  'panelStickyScroll.shadow': alpha(stage.darkness, '50'),
  'outputView.background': blacks.void,
  'outputViewStickyScroll.background': blacks.void,
  'activityWarningBadge.foreground': blacks.void,
  'activityWarningBadge.background': semantic.warning,
  'activityErrorBadge.foreground': stage.spotlight,
  'activityErrorBadge.background': semantic.error,
  'commandCenter.debuggingBackground': alpha(pinks.sekai, '25'),
  'list.dropBackground': alpha(teals.classic, '20'),
  'list.dropBetweenBackground': alpha(teals.classic, '40'),
  'list.focusAndSelectionOutline': alpha(pinks.sekai, '60'),
  'list.inactiveSelectionIconForeground': foregrounds.primary,
  'list.inactiveFocusBackground': alpha(teals.classic, '15'),
  'list.inactiveFocusOutline': alpha(teals.classic, '30'),
  'list.filterMatchBackground': alpha(pinks.sekai, '25'),
  'list.filterMatchBorder': alpha(pinks.sekai, '50'),
  'listFilterWidget.shadow': alpha(stage.darkness, '50'),
  'tree.inactiveIndentGuidesStroke': alpha(teals.classic, '15'),
  'tree.tableOddRowsBackground': alpha(teals.classic, '05'),
  'badge.foreground': blacks.void,
  'badge.background': character.hair.tip,
  'progressBar.background': artStyles.ixima.techCyan,
  'editor.placeholder.foreground': alpha(foregrounds.comment, '60'),
  'editor.inactiveSelectionBackground': alpha(teals.classic, '20'),
  'editor.wordHighlightTextBackground': alpha(cyans.ice, '15'),
  'editor.wordHighlightTextBorder': alpha(cyans.ice, '35'),
  'editor.findMatchForeground': pinks.blush,
  'editor.findMatchHighlightForeground': stage.spotlight,
  'editor.findRangeHighlightBorder': alpha(teals.classic, '40'),
  'search.resultsInfoForeground': foregrounds.primary,
  'editorStickyScroll.shadow': alpha(stage.darkness, '30'),
  'editorStickyScrollGutter.background': alpha(blacks.outfit, 'F0'),
  'commentsView.resolvedIcon': semantic.success,
  'commentsView.unresolvedIcon': semantic.warning,
  'terminal.hoverHighlightBackground': alpha(teals.classic, '20'),
  'terminal.initialHintForeground': alpha(teals.neon, '80'),
  'terminal.selectionForeground': stage.spotlight,
  'terminal.dropBackground': alpha(teals.classic, '20'),
  'terminalCommandGuide.foreground': alpha(teals.classic, '40'),
  'terminalOverviewRuler.border': alpha(teals.classic, '30'),
  'terminalStickyScroll.background': blacks.void,
  'terminalStickyScroll.border': alpha(teals.classic, '20'),
  'terminalStickyScrollHover.background': alpha(versionMapping.hover, '15'),
  'sideBarTitle.background': character.headphones.frame,
  'sideBarTitle.border': alpha(teals.classic, '15'),
  'sideBarActivityBarTop.border': alpha(teals.classic, '15'),
  'peekViewEditorStickyScroll.background': blacks.outfit,
  'peekViewEditorStickyScrollGutter.background': blacks.sleeve,
  'debugExceptionWidget.background': alpha(semantic.error, '20'),
  'debugExceptionWidget.border': semantic.error,
  'editor.inlineValuesForeground': versions.v6ai,
  'editor.inlineValuesBackground': alpha(versions.v6ai, '15'),
  'debugTokenExpression.type': pinks.pale,
  'minimap.chatEditHighlight': alpha(versions.v6ai, '60'),
  'editorMinimap.inlineChatInserted': alpha(versions.v6ai, '50'),
  'diffEditor.unchangedRegionShadow': alpha(stage.darkness, '30'),
  'diffEditor.move.border': alpha(hologram.purple, '60'),
  'diffEditor.moveActive.border': hologram.purple,
  'sideBySideEditor.horizontalBorder': alpha(teals.classic, '25'),
  'sideBySideEditor.verticalBorder': alpha(teals.classic, '25'),
  'editorPane.background': blacks.outfit,
  'editorGroup.dropIntoPromptForeground': foregrounds.primary,
  'editorGroup.dropIntoPromptBackground': alpha(blacks.outfit, 'F0'),
  'editorGroup.dropIntoPromptBorder': alpha(teals.classic, '50'),
  'editorGroup.emptyBackground': blacks.base,
  'editorGroup.focusedEmptyBorder': alpha(teals.classic, '40'),
  'git.blame.editorDecorationForeground': alpha(foregrounds.comment, '60'),
  'walkthrough.stepTitle.foreground': character.skin.base,
  'settings.settingsHeaderHoverForeground': character.hair.tip,
  'profiles.sashBorder': alpha(teals.classic, '30'),
  'simpleFindWidget.sashBorder': alpha(teals.classic, '40'),
  'contrastActiveBorder': alpha(character.hair.highlight, 'CC'),
  'contrastBorder': alpha(teals.classic, '60'),
  'widget.border': alpha(teals.classic, '40'),
  'window.activeBorder': alpha(teals.classic, '60'),
  'window.inactiveBorder': alpha(teals.classic, '30'),
  'textPreformat.background': alpha(blacks.sleeve, '80'),
  'textPreformat.border': alpha(teals.classic, '30'),
  'button.separator': alpha(blacks.void, '60'),
  'scrollbar.background': alpha(blacks.base, '00'),
  'list.focusHighlightForeground': character.hair.highlight,
  'activityBar.activeFocusBorder': pinks.sekai,
  'activityBar.dropBorder': alpha(teals.classic, '60'),
  'activityBarTop.activeBackground': alpha(v4xVoice.hard, '20'),
  'activityBarTop.background': blacks.void,
  'activityBarTop.dropBorder': alpha(teals.classic, '60'),
  'editorGroupHeader.border': alpha(teals.classic, '20'),
  'tab.unfocusedActiveBorder': alpha(teals.classic, '40'),
  'tab.unfocusedHoverBackground': alpha(pinks.sekai, '10'),
  'tab.unfocusedHoverBorder': alpha(pinks.sekai, '30'),
  'tab.unfocusedHoverForeground': append.light,
  'editor.compositionBorder': alpha(teals.classic, '60'),
  'editor.findRangeHighlightBackground': alpha(teals.classic, '15'),
  'editor.inactiveLineHighlightBackground': alpha(versionMapping.identity, '08'),
  'editor.selectionForeground': stage.spotlight,
  'editorIndentGuide.activeBackground': alpha(teals.classic, '50'),
  'editorIndentGuide.background': alpha(teals.classic, '20'),
  'editorOverviewRuler.background': blacks.base,
  'editorOverviewRuler.border': alpha(teals.classic, '20'),
  'editorOverviewRuler.commentDraftForeground': alpha(foregrounds.comment, '50'),
  'editorOverviewRuler.commonContentForeground': alpha(greys.slate, '60'),
  'editorOverviewRuler.currentContentForeground': alpha(hologram.cyan, '80'),
  'editorOverviewRuler.incomingContentForeground': alpha(pinks.sekai, '80'),
  'editorOverviewRuler.rangeHighlightForeground': alpha(teals.classic, '60'),
  'editorUnnecessaryCode.border': alpha(greys.silver, '40'),
  'editorGutter.background': blacks.base,
  'editorGutter.commentDraftGlyphForeground': alpha(hologram.cyan, '80'),
  'editorGutter.itemBackground': alpha(teals.classic, '15'),
  'editorGutter.itemGlyphForeground': teals.classic,
  'diffEditor.insertedTextBorder': alpha(character.negi.bright, '50'),
  'diffEditor.removedTextBorder': alpha(character.headphones.cushion, '50'),
  'inlineChat.foreground': foregrounds.primary,
  'editorSuggestWidgetStatus.foreground': greys.silver,
  'panelTitle.border': alpha(pinks.sekai, '30'),
  'statusBar.focusBorder': alpha(character.hair.highlight, 'DD'),
  'statusBarItem.errorHoverForeground': stage.spotlight,
  'statusBarItem.offlineBackground': greys.slate,
  'statusBarItem.offlineForeground': greys.platinum,
  'statusBarItem.offlineHoverBackground': alpha(greys.slate, 'CC'),
  'statusBarItem.offlineHoverForeground': stage.spotlight,
  'statusBarItem.remoteHoverForeground': stage.spotlight,
  'statusBarItem.warningHoverForeground': blacks.void,
  'extensionButton.background': teals.classic,
  'extensionButton.foreground': blacks.void,
  'extensionButton.hoverBackground': teals.stage,
  'extensionIcon.privateForeground': greys.silver,
  'mcpIcon.starForeground': semantic.warning,
  'scmGraph.historyItemHoverLabelForeground': foregrounds.primary,
  'chart.axis': alpha(teals.classic, '80'),
  'chart.guide': alpha(teals.classic, '30'),
  'chart.line': teals.classic,
  'gauge.background': blacks.sleeve,
  'gauge.border': alpha(teals.classic, '40'),
  'gauge.errorBackground': alpha(semantic.error, '30'),
  'gauge.errorForeground': boosted.coralGlow,
  'gauge.foreground': teals.classic,
  'gauge.warningBackground': alpha(semantic.warning, '30'),
  'gauge.warningForeground': semantic.warning,
  'markdownAlert.caution.foreground': boosted.coralGlow,
  'markdownAlert.important.foreground': boosted.purple,
  'markdownAlert.note.foreground': semantic.info,
  'markdownAlert.tip.foreground': semantic.success,
  'markdownAlert.warning.foreground': semantic.warning,
  'agentSessionReadIndicator.foreground': teals.classic,
  'agentSessionSelectedBadge.border': pinks.sekai,
  'agentSessionSelectedUnfocusedBadge.border': alpha(pinks.sekai, '60'),
  'notebook.focusedCellBackground': alpha(teals.classic, '10'),
  'notebook.inactiveSelectedCellBorder': alpha(teals.classic, '40'),
  'notebookScrollbarSlider.activeBackground': alpha(character.hair.shadow, '80'),
  'notebookScrollbarSlider.background': alpha(character.boots.hardware, '40'),
  'notebookScrollbarSlider.hoverBackground': alpha(character.top.main, '60'),
  'outputsNotebook.border': alpha(teals.classic, '30'),
} as const;
export type WorkbenchColors = typeof workbenchColors;
