import { character } from '../palette';

const alpha = (hex: string, opacity: string): string => `${hex}${opacity}`;

export const workbenchColors = {
  'editor.background': character.hair.base,
  'editor.foreground': character.hair.base,
  'editorCursor.foreground': character.hair.base,
  'editorCursor.background': character.hair.base,
  'editorMultiCursor.primary.foreground': character.hair.base,
  'editorMultiCursor.primary.background': character.hair.base,
  'editorMultiCursor.secondary.foreground': character.hair.base,
  'editorMultiCursor.secondary.background': character.hair.base,
  'editor.lineHighlightBackground': alpha(character.hair.base, '12'),
  'editor.lineHighlightBorder': alpha(character.hair.base, '30'),
  'editor.selectionBackground': alpha(character.hair.base, '35'),
  'editor.selectionHighlightBackground': alpha(character.hair.base, '25'),
  'editor.selectionHighlightBorder': alpha(character.hair.base, '40'),
  'editor.wordHighlightBackground': alpha(character.hair.base, '20'),
  'editor.wordHighlightBorder': alpha(character.hair.base, '40'),
  'editor.wordHighlightStrongBackground': alpha(character.hair.base, '30'),
  'editor.wordHighlightStrongBorder': alpha(character.hair.base, '60'),
  'editor.findMatchBackground': alpha(character.hair.base, '60'),
  'editor.findMatchBorder': alpha(character.hair.base, '90'),
  'editor.findMatchHighlightBackground': alpha(character.hair.base, '50'),
  'editor.findMatchHighlightBorder': alpha(character.hair.base, '80'),
  'editor.rangeHighlightBackground': alpha(character.hair.base, '10'),
  'editor.rangeHighlightBorder': alpha(character.hair.base, '30'),
  'editorLineNumber.foreground': character.hair.base,
  'editorLineNumber.activeForeground': character.hair.base,
  'editorLineNumber.dimmedForeground': character.hair.base,
  'editorIndentGuide.background1': alpha(character.hair.base, '50'),
  'editorIndentGuide.background2': alpha(character.hair.base, '55'),
  'editorIndentGuide.background3': alpha(character.hair.base, '60'),
  'editorIndentGuide.background4': alpha(character.hair.base, '65'),
  'editorIndentGuide.background5': alpha(character.hair.base, '70'),
  'editorIndentGuide.background6': alpha(character.hair.base, '75'),
  'editorIndentGuide.activeBackground1': character.hair.base,
  'editorIndentGuide.activeBackground2': character.hair.base,
  'editorIndentGuide.activeBackground3': character.hair.base,
  'editorIndentGuide.activeBackground4': character.hair.base,
  'editorIndentGuide.activeBackground5': character.hair.base,
  'editorIndentGuide.activeBackground6': character.hair.base,
  'editorRuler.foreground': character.hair.base,
  'editorWhitespace.foreground': character.hair.base,
  'editorBracketMatch.background': alpha(character.hair.base, '25'),
  'editorBracketMatch.border': character.hair.base,
  'editorBracketHighlight.foreground1': character.hair.base,
  'editorBracketHighlight.foreground2': character.hair.base,
  'editorBracketHighlight.foreground3': character.hair.base,
  'editorBracketHighlight.foreground4': character.hair.base,
  'editorBracketHighlight.foreground5': character.hair.base,
  'editorBracketHighlight.foreground6': character.hair.base,
  'editorBracketHighlight.unexpectedBracket.foreground': character.hair.base,
  'editorBracketPairGuide.background1': alpha(character.hair.base, '25'),
  'editorBracketPairGuide.background2': alpha(character.hair.base, '25'),
  'editorBracketPairGuide.background3': alpha(character.hair.base, '25'),
  'editorBracketPairGuide.background4': alpha(character.hair.base, '25'),
  'editorBracketPairGuide.background5': alpha(character.hair.base, '25'),
  'editorBracketPairGuide.background6': alpha(character.hair.base, '25'),
  'editorBracketPairGuide.activeBackground1': alpha(character.hair.base, '50'),
  'editorBracketPairGuide.activeBackground2': alpha(character.hair.base, '50'),
  'editorBracketPairGuide.activeBackground3': alpha(character.hair.base, '50'),
  'editorBracketPairGuide.activeBackground4': alpha(character.hair.base, '50'),
  'editorBracketPairGuide.activeBackground5': alpha(character.hair.base, '50'),
  'editorBracketPairGuide.activeBackground6': alpha(character.hair.base, '50'),
  'editorGutter.addedBackground': alpha(character.hair.base, '80'),
  'editorGutter.modifiedBackground': alpha(character.hair.base, '80'),
  'editorGutter.deletedBackground': alpha(character.hair.base, '80'),
  'editorGutter.foldingControlForeground': alpha(character.hair.base, 'BB'),
  'editorWidget.background': character.hair.base,
  'editorWidget.foreground': character.hair.base,
  'editorWidget.border': alpha(character.hair.base, '80'),
  'editorWidget.resizeBorder': alpha(character.hair.base, '80'),
  'editorHoverWidget.background': alpha(character.hair.base, 'F5'),
  'editorHoverWidget.border': alpha(character.hair.base, '70'),
  'editorHoverWidget.foreground': character.hair.base,
  'editorHoverWidget.highlightForeground': character.hair.base,
  'editorHoverWidget.statusBarBackground': character.hair.base,
  'editorUnnecessaryCode.opacity': alpha(character.hair.base, '80'),
  'editorGhostText.foreground': alpha(character.hair.base, 'BB'),
  'editorGhostText.border': alpha(character.hair.base, '40'),
  'editorGhostText.background': alpha(character.hair.base, '0A'),
  'editor.linkedEditingBackground': alpha(character.hair.base, '20'),
  'editorOverviewRuler.bracketMatchForeground': alpha(character.hair.base, 'A0'),
  'editorOverviewRuler.wordHighlightForeground': alpha(character.hair.base, '80'),
  'editorOverviewRuler.wordHighlightStrongForeground': alpha(character.hair.base, '90'),
  'editorOverviewRuler.wordHighlightTextForeground': alpha(character.hair.base, '60'),
  'editorOverviewRuler.findMatchForeground': alpha(character.hair.base, '90'),
  'editorOverviewRuler.selectionHighlightForeground': alpha(character.hair.base, '50'),
  'editorOverviewRuler.infoForeground': character.hair.base,
  'editorOverviewRuler.warningForeground': character.hair.base,
  'editorOverviewRuler.errorForeground': character.hair.base,
  'editorLink.activeForeground': character.hair.base,
  'editorCodeLens.foreground': alpha(character.hair.base, 'CC'),
  // Activity Bar - Snow Miku 2017 (Twinkle Snow - Starry constellation)
  'activityBar.background': character.hair.base,
  'activityBar.foreground': character.hair.base,
  'activityBar.activeBorder': character.hair.base,
  'activityBar.activeBackground': alpha(character.hair.base, '20'),
  'activityBar.inactiveForeground': character.hair.base,
  'activityBar.border': alpha(character.hair.base, '60'),
  'activityBarBadge.background': character.hair.base,
  'activityBarBadge.foreground': character.hair.base,
  'activityBarTop.foreground': character.hair.base,
  'activityBarTop.activeBorder': character.hair.base,
  'activityBarTop.inactiveForeground': character.hair.base,
  // Sidebar - Snow Miku 2019 (Princess - Winter night royalty)
  'sideBar.background': character.hair.base,
  'sideBar.foreground': character.hair.base,
  'sideBar.border': alpha(character.hair.base, '50'),
  'sideBar.dropBackground': alpha(character.hair.base, '20'),
  'sideBarSectionHeader.background': character.hair.base,
  'sideBarSectionHeader.foreground': character.hair.base,
  'sideBarSectionHeader.border': alpha(character.hair.base, '25'),
  'sideBarTitle.foreground': character.hair.base,
  'sideBarStickyScroll.background': character.hair.base,
  'sideBarStickyScroll.border': alpha(character.hair.base, '20'),
  'sideBarStickyScroll.shadow': alpha(character.hair.base, '50'),
  // Status Bar - Digital Stars 2024 (BUNBUN Cyber Sporty)
  'statusBar.background': character.hair.base,
  'statusBar.foreground': character.hair.base,
  'statusBar.border': alpha(character.hair.base, '70'),
  'statusBar.debuggingBackground': character.hair.base,
  'statusBar.debuggingForeground': character.hair.base,
  'statusBar.debuggingBorder': character.hair.base,
  'statusBar.noFolderBackground': character.hair.base,
  'statusBar.noFolderForeground': character.hair.base,
  'statusBar.noFolderBorder': alpha(character.hair.base, '40'),
  'statusBarItem.remoteBackground': character.hair.base,
  'statusBarItem.remoteForeground': character.hair.base,
  'statusBarItem.remoteHoverBackground': character.hair.base,
  'statusBarItem.hoverBackground': alpha(character.hair.base, '20'),
  'statusBarItem.hoverForeground': character.hair.base,
  'statusBarItem.activeBackground': alpha(character.hair.base, '40'),
  'statusBarItem.errorBackground': character.hair.base,
  'statusBarItem.errorForeground': character.hair.base,
  'statusBarItem.errorHoverBackground': alpha(character.hair.base, 'CC'),
  'statusBarItem.warningBackground': character.hair.base,
  'statusBarItem.warningForeground': character.hair.base,
  'statusBarItem.warningHoverBackground': alpha(character.hair.base, 'CC'),
  'statusBarItem.prominentBackground': alpha(character.hair.base, '25'),
  'statusBarItem.prominentForeground': character.hair.base,
  'statusBarItem.prominentHoverBackground': alpha(character.hair.base, '40'),
  'statusBarItem.prominentHoverForeground': character.hair.base,
  'statusBarItem.compactHoverBackground': alpha(character.hair.base, '30'),
  'statusBarItem.focusBorder': alpha(character.hair.base, 'DD'),
  // Title Bar - Miku V2 (2007 Original Turquoise)
  'titleBar.activeBackground': character.hair.base,
  'titleBar.activeForeground': character.hair.base,
  'titleBar.inactiveBackground': character.hair.base,
  'titleBar.inactiveForeground': alpha(character.hair.base, '70'),
  'titleBar.border': alpha(character.hair.base, '30'),
  'menubar.selectionForeground': character.hair.base,
  'menubar.selectionBackground': alpha(character.hair.base, '30'),
  'menubar.selectionBorder': alpha(character.hair.base, '60'),
  // Tabs - Miku Expo 2026 (Candy Pop - Sweet colorful celebration)
  'tab.activeBackground': alpha(character.hair.base, '10'),
  'tab.activeForeground': character.hair.base,
  'tab.activeBorderTop': character.hair.base,
  'tab.activeBorder': alpha(character.hair.base, '40'),
  'tab.inactiveBackground': character.hair.base,
  'tab.inactiveForeground': character.hair.base,
  'tab.border': character.hair.base,
  'tab.hoverBackground': alpha(character.hair.base, '15'),
  'tab.hoverForeground': character.hair.base,
  'tab.hoverBorder': alpha(character.hair.base, '40'),
  'tab.unfocusedActiveBackground': character.hair.base,
  'tab.unfocusedActiveForeground': character.hair.base,
  'tab.unfocusedActiveBorderTop': alpha(character.hair.base, '80'),
  'tab.unfocusedInactiveBackground': character.hair.base,
  'tab.unfocusedInactiveForeground': character.hair.base,
  'editorGroupHeader.tabsBackground': character.hair.base,
  'editorGroupHeader.tabsBorder': alpha(character.hair.base, '15'),
  'editorGroupHeader.noTabsBackground': character.hair.base,
  'editorGroup.border': alpha(character.hair.base, '60'),
  'editorGroup.dropBackground': alpha(character.hair.base, '40'),
  // Lists - Snow Miku 2023 (Serene Winter - Kimono elegance)
  'list.activeSelectionBackground': alpha(character.hair.base, '30'),
  'list.activeSelectionForeground': character.hair.base,
  'list.activeSelectionIconForeground': character.hair.base,
  'list.inactiveSelectionBackground': alpha(character.hair.base, '20'),
  'list.inactiveSelectionForeground': character.hair.base,
  'list.hoverBackground': alpha(character.hair.base, '15'),
  'list.hoverForeground': character.hair.base,
  'list.focusBackground': alpha(character.hair.base, '25'),
  'list.focusForeground': character.hair.base,
  'list.focusOutline': alpha(character.hair.base, 'DD'),
  'list.highlightForeground': character.hair.base,
  'list.errorForeground': character.hair.base,
  'list.warningForeground': character.hair.base,
  'list.invalidItemForeground': character.hair.base,
  'list.deemphasizedForeground': character.hair.base,
  'listFilterWidget.background': character.hair.base,
  'listFilterWidget.outline': alpha(character.hair.base, '70'),
  'listFilterWidget.noMatchesOutline': character.hair.base,
  'tree.indentGuidesStroke': alpha(character.hair.base, '40'),
  'tree.tableColumnsBorder': alpha(character.hair.base, '25'),
  'focusBorder': character.hair.base,
  'foreground': character.hair.base,
  'disabledForeground': character.hair.base,
  'widget.shadow': alpha(character.hair.base, '70'),
  'selection.background': alpha(character.hair.base, '40'),
  'descriptionForeground': character.hair.base,
  'errorForeground': character.hair.base,
  'icon.foreground': character.hair.base,
  'sash.hoverBorder': alpha(character.hair.base, '80'),
  // Input - Snow Miku 2026 (Pâtisserie - Sweet pastry theme)
  'input.background': character.hair.base,
  'input.foreground': character.hair.base,
  'input.border': alpha(character.hair.base, '50'),
  'input.placeholderForeground': character.hair.base,
  'inputOption.activeBorder': character.hair.base,
  'inputOption.activeBackground': alpha(character.hair.base, '30'),
  'inputOption.activeForeground': character.hair.base,
  'inputOption.hoverBackground': alpha(character.hair.base, '20'),
  'inputValidation.errorBackground': alpha(character.hair.base, '25'),
  'inputValidation.errorBorder': character.hair.base,
  'inputValidation.errorForeground': character.hair.base,
  'inputValidation.warningBackground': alpha(character.hair.base, '25'),
  'inputValidation.warningBorder': character.hair.base,
  'inputValidation.warningForeground': character.hair.base,
  'inputValidation.infoBackground': alpha(character.hair.base, '25'),
  'inputValidation.infoBorder': character.hair.base,
  'inputValidation.infoForeground': character.hair.base,
  // Dropdown - Miku Expo 2020 Europe
  'dropdown.background': character.hair.base,
  'dropdown.foreground': character.hair.base,
  'dropdown.border': alpha(character.hair.base, '50'),
  'dropdown.listBackground': character.hair.base,
  // Buttons - Magical Mirai 2018 (Mika Pikazo)
  'button.background': character.hair.base,
  'button.foreground': character.hair.base,
  'button.hoverBackground': character.hair.base,
  'button.secondaryBackground': character.hair.base,
  'button.secondaryForeground': character.hair.base,
  'button.secondaryHoverBackground': character.hair.base,
  'button.border': alpha(character.hair.base, '80'),
  'checkbox.background': character.hair.base,
  'checkbox.foreground': character.hair.base,
  'checkbox.border': alpha(character.hair.base, '50'),
  // Scrollbar - Snow Miku 2018 (Crane - Red obi & gold bell)
  'scrollbar.shadow': alpha(character.hair.base, '50'),
  'scrollbarSlider.background': alpha(character.hair.base, '40'),
  'scrollbarSlider.hoverBackground': alpha(character.hair.base, '60'),
  'scrollbarSlider.activeBackground': alpha(character.hair.base, '80'),
  // Minimap - Snow Miku 2016 (Owl - Amber goggles & cyan)
  'minimap.findMatchHighlight': alpha(character.hair.base, '90'),
  'minimap.selectionHighlight': alpha(character.hair.base, '70'),
  'minimap.errorHighlight': alpha(character.hair.base, '95'),
  'minimap.warningHighlight': alpha(character.hair.base, '90'),
  'minimap.background': alpha(character.hair.base, '08'),
  'minimap.selectionOccurrenceHighlight': alpha(character.hair.base, '50'),
  'minimap.foregroundOpacity': alpha(character.hair.base, 'BB'),
  'minimap.infoHighlight': alpha(character.hair.base, '80'),
  'minimapSlider.background': alpha(character.hair.base, '20'),
  'minimapSlider.hoverBackground': alpha(character.hair.base, '40'),
  'minimapSlider.activeBackground': alpha(character.hair.base, '45'),
  'minimapGutter.addedBackground': alpha(character.hair.base, '90'),
  'minimapGutter.modifiedBackground': alpha(character.hair.base, '90'),
  'minimapGutter.deletedBackground': alpha(character.hair.base, '90'),
  // Breadcrumbs - Snow Miku 2015 (Bell - Fresh green & cyan)
  'breadcrumb.foreground': character.hair.base,
  'breadcrumb.background': character.hair.base,
  'breadcrumb.focusForeground': character.hair.base,
  'breadcrumb.activeSelectionForeground': character.hair.base,
  'breadcrumbPicker.background': character.hair.base,
  'terminal.background': character.hair.base,
  'terminal.foreground': character.hair.base,
  'terminal.ansiBlack': character.hair.base,
  'terminal.ansiRed': character.hair.base,
  'terminal.ansiGreen': character.hair.base,
  'terminal.ansiYellow': character.hair.base,
  'terminal.ansiBlue': character.hair.base,
  'terminal.ansiMagenta': character.hair.base,
  'terminal.ansiCyan': character.hair.base,
  'terminal.ansiWhite': character.hair.base,
  'terminal.ansiBrightBlack': character.hair.base,
  'terminal.ansiBrightRed': character.hair.base,
  'terminal.ansiBrightGreen': character.hair.base,
  'terminal.ansiBrightYellow': character.hair.base,
  'terminal.ansiBrightBlue': character.hair.base,
  'terminal.ansiBrightMagenta': character.hair.base,
  'terminal.ansiBrightCyan': character.hair.base,
  'terminal.ansiBrightWhite': character.hair.base,
  'terminal.selectionBackground': alpha(character.hair.base, '40'),
  'terminal.inactiveSelectionBackground': alpha(character.hair.base, '25'),
  'terminal.findMatchBackground': alpha(character.hair.base, '50'),
  'terminal.findMatchBorder': alpha(character.hair.base, '90'),
  'terminal.findMatchHighlightBackground': alpha(character.hair.base, '30'),
  'terminal.findMatchHighlightBorder': alpha(character.hair.base, '60'),
  'terminalCursor.foreground': character.hair.base,
  'terminalCursor.background': character.hair.base,
  'terminal.border': alpha(character.hair.base, '60'),
  'terminal.tab.activeBorder': character.hair.base,
  'terminalCommandDecoration.defaultBackground': alpha(character.hair.base, '60'),
  'terminalCommandDecoration.successBackground': alpha(character.hair.base, '90'),
  'terminalCommandDecoration.errorBackground': alpha(character.hair.base, '90'),
  'terminalOverviewRuler.cursorForeground': character.hair.base,
  'terminalOverviewRuler.findMatchForeground': alpha(character.hair.base, '80'),
  'textLink.foreground': character.hair.base,
  'textLink.activeForeground': character.hair.base,
  'textBlockQuote.background': character.hair.base,
  'textBlockQuote.border': alpha(character.hair.base, '60'),
  'textCodeBlock.background': character.hair.base,
  'textPreformat.foreground': character.hair.base,
  'textSeparator.foreground': alpha(character.hair.base, '30'),
  'notifications.background': alpha(character.hair.base, 'F5'),
  'notifications.foreground': character.hair.base,
  'notifications.border': alpha(character.hair.base, '70'),
  'notificationToast.border': alpha(character.hair.base, '80'),
  'notificationsInfoIcon.foreground': character.hair.base,
  'notificationsWarningIcon.foreground': character.hair.base,
  'notificationsErrorIcon.foreground': character.hair.base,
  'notificationLink.foreground': character.hair.base,
  'notificationCenterHeader.background': alpha(character.hair.base, 'F0'),
  'notificationCenterHeader.foreground': character.hair.base,
  'notificationCenter.border': alpha(character.hair.base, '60'),
  'peekView.border': alpha(character.hair.base, '90'),
  'peekViewEditor.background': character.hair.base,
  'peekViewEditorGutter.background': character.hair.base,
  'peekViewResult.background': character.hair.base,
  'peekViewResult.selectionBackground': alpha(character.hair.base, '30'),
  'peekViewResult.selectionForeground': character.hair.base,
  'peekViewTitle.background': character.hair.base,
  'peekViewTitleLabel.foreground': character.hair.base,
  'peekViewTitleDescription.foreground': character.hair.base,
  'peekViewResult.fileForeground': character.hair.base,
  'peekViewResult.lineForeground': character.hair.base,
  'peekViewResult.matchHighlightBackground': alpha(character.hair.base, '50'),
  'peekViewEditor.matchHighlightBackground': alpha(character.hair.base, '50'),
  'peekViewEditor.matchHighlightBorder': alpha(character.hair.base, '80'),
  'pickerGroup.border': alpha(character.hair.base, '30'),
  'pickerGroup.foreground': character.hair.base,
  'gitDecoration.addedResourceForeground': character.hair.base,
  'gitDecoration.modifiedResourceForeground': character.hair.base,
  'gitDecoration.deletedResourceForeground': character.hair.base,
  'gitDecoration.renamedResourceForeground': character.hair.base,
  'gitDecoration.untrackedResourceForeground': character.hair.base,
  'gitDecoration.ignoredResourceForeground': character.hair.base,
  'gitDecoration.conflictingResourceForeground': character.hair.base,
  'gitDecoration.stageModifiedResourceForeground': character.hair.base,
  'gitDecoration.stageDeletedResourceForeground': character.hair.base,
  'gitDecoration.submoduleResourceForeground': character.hair.base,
  'diffEditor.insertedTextBackground': alpha(character.hair.base, '30'),
  'diffEditor.removedTextBackground': alpha(character.hair.base, '30'),
  'diffEditor.insertedLineBackground': alpha(character.hair.base, '20'),
  'diffEditor.removedLineBackground': alpha(character.hair.base, '18'),
  'diffEditor.diagonalFill': alpha(character.hair.base, '15'),
  'diffEditor.border': alpha(character.hair.base, '60'),
  'diffEditor.unchangedRegionBackground': character.hair.base,
  'diffEditor.unchangedRegionForeground': character.hair.base,
  'diffEditor.unchangedCodeBackground': alpha(character.hair.base, '08'),
  'diffEditorGutter.insertedLineBackground': alpha(character.hair.base, '50'),
  'diffEditorGutter.removedLineBackground': alpha(character.hair.base, '40'),
  'diffEditorOverview.insertedForeground': character.hair.base,
  'diffEditorOverview.removedForeground': character.hair.base,
  'multiDiffEditor.headerBackground': character.hair.base,
  'multiDiffEditor.background': character.hair.base,
  'multiDiffEditor.border': alpha(character.hair.base, '30'),
  'panel.background': character.hair.base,
  'panel.border': alpha(character.hair.base, '70'),
  'panel.dropBorder': alpha(character.hair.base, 'DD'),
  'panelTitle.activeForeground': character.hair.base,
  'panelTitle.inactiveForeground': character.hair.base,
  'panelTitle.activeBorder': character.hair.base,
  'panelInput.border': alpha(character.hair.base, '40'),
  'panelSection.border': alpha(character.hair.base, '35'),
  'panelSection.dropBackground': alpha(character.hair.base, '25'),
  'panelSectionHeader.background': character.hair.base,
  'panelSectionHeader.foreground': character.hair.base,
  'panelSectionHeader.border': alpha(character.hair.base, '20'),
  'debugToolBar.background': alpha(character.hair.base, '20'),
  'debugToolBar.border': alpha(character.hair.base, '60'),
  'debugIcon.breakpointForeground': character.hair.base,
  'debugIcon.breakpointDisabledForeground': alpha(character.hair.base, '50'),
  'debugIcon.breakpointUnverifiedForeground': character.hair.base,
  'debugIcon.breakpointCurrentStackframeForeground': character.hair.base,
  'debugIcon.breakpointStackframeForeground': character.hair.base,
  'debugIcon.startForeground': character.hair.base,
  'debugIcon.pauseForeground': character.hair.base,
  'debugIcon.stopForeground': character.hair.base,
  'debugIcon.disconnectForeground': character.hair.base,
  'debugIcon.restartForeground': character.hair.base,
  'debugIcon.stepOverForeground': character.hair.base,
  'debugIcon.stepIntoForeground': character.hair.base,
  'debugIcon.stepOutForeground': character.hair.base,
  'debugIcon.stepBackForeground': character.hair.base,
  'debugIcon.continueForeground': character.hair.base,
  'debugConsole.infoForeground': character.hair.base,
  'debugConsole.warningForeground': character.hair.base,
  'debugConsole.errorForeground': character.hair.base,
  'debugConsole.sourceForeground': character.hair.base,
  'debugConsoleInputIcon.foreground': character.hair.base,
  'debugTokenExpression.name': character.hair.base,
  'debugTokenExpression.value': character.hair.base,
  'debugTokenExpression.string': character.hair.base,
  'debugTokenExpression.number': character.hair.base,
  'debugTokenExpression.boolean': character.hair.base,
  'debugTokenExpression.error': character.hair.base,
  'debugView.exceptionLabelForeground': character.hair.base,
  'debugView.exceptionLabelBackground': character.hair.base,
  'debugView.stateLabelForeground': character.hair.base,
  'debugView.stateLabelBackground': alpha(character.hair.base, '40'),
  'debugView.valueChangedHighlight': alpha(character.hair.base, '80'),
  'editor.stackFrameHighlightBackground': alpha(character.hair.base, '25'),
  'editor.focusedStackFrameHighlightBackground': alpha(character.hair.base, '20'),
  'testing.iconFailed': character.hair.base,
  'testing.iconErrored': character.hair.base,
  'testing.iconPassed': character.hair.base,
  'testing.iconQueued': character.hair.base,
  'testing.iconUnset': character.hair.base,
  'testing.iconSkipped': character.hair.base,
  'testing.runAction': character.hair.base,
  'testing.peekBorder': character.hair.base,
  'testing.peekHeaderBackground': character.hair.base,
  'testing.message.error.decorationForeground': character.hair.base,
  'testing.message.error.lineBackground': alpha(character.hair.base, '15'),
  'testing.message.info.decorationForeground': character.hair.base,
  'testing.message.info.lineBackground': alpha(character.hair.base, '15'),
  'mergeEditor.change.background': alpha(character.hair.base, '15'),
  'mergeEditor.change.word.background': alpha(character.hair.base, '30'),
  'mergeEditor.conflict.handled.minimapOverViewRuler': character.hair.base,
  'mergeEditor.conflict.handledFocused.border': character.hair.base,
  'mergeEditor.conflict.handledUnfocused.border': alpha(character.hair.base, '80'),
  'mergeEditor.conflict.unhandled.minimapOverViewRuler': character.hair.base,
  'mergeEditor.conflict.unhandledFocused.border': character.hair.base,
  'mergeEditor.conflict.unhandledUnfocused.border': alpha(character.hair.base, '80'),
  'mergeEditor.conflictingLines.background': alpha(character.hair.base, '15'),
  'settings.headerForeground': character.hair.base,
  'settings.modifiedItemIndicator': character.hair.base,
  'settings.focusedRowBackground': alpha(character.hair.base, '10'),
  'settings.rowHoverBackground': alpha(character.hair.base, '08'),
  'settings.focusedRowBorder': alpha(character.hair.base, '40'),
  'settings.headerBorder': alpha(character.hair.base, '20'),
  'settings.sashBorder': alpha(character.hair.base, '30'),
  'settings.dropdownBackground': character.hair.base,
  'settings.dropdownForeground': character.hair.base,
  'settings.dropdownBorder': alpha(character.hair.base, '40'),
  'settings.dropdownListBorder': alpha(character.hair.base, '40'),
  'settings.checkboxBackground': character.hair.base,
  'settings.checkboxForeground': character.hair.base,
  'settings.checkboxBorder': alpha(character.hair.base, '40'),
  'settings.textInputBackground': character.hair.base,
  'settings.textInputForeground': character.hair.base,
  'settings.textInputBorder': alpha(character.hair.base, '40'),
  'settings.numberInputBackground': character.hair.base,
  'settings.numberInputForeground': character.hair.base,
  'settings.numberInputBorder': alpha(character.hair.base, '40'),
  'welcomePage.background': character.hair.base,
  'welcomePage.tileBackground': character.hair.base,
  'welcomePage.tileBorder': alpha(character.hair.base, '30'),
  'welcomePage.tileHoverBackground': alpha(character.hair.base, '10'),
  'welcomePage.progress.foreground': character.hair.base,
  'welcomePage.progress.background': character.hair.base,
  'walkThrough.embeddedEditorBackground': character.hair.base,
  'extensionButton.prominentBackground': character.hair.base,
  'extensionButton.prominentForeground': character.hair.base,
  'extensionButton.prominentHoverBackground': character.hair.base,
  'extensionButton.separator': character.hair.base,
  'extensionBadge.remoteBackground': character.hair.base,
  'extensionBadge.remoteForeground': character.hair.base,
  'extensionIcon.starForeground': character.hair.base,
  'extensionIcon.verifiedForeground': character.hair.base,
  'extensionIcon.preReleaseForeground': character.hair.base,
  'extensionIcon.sponsorForeground': character.hair.base,
  'keybindingLabel.background': alpha(character.hair.base, '20'),
  'keybindingLabel.foreground': character.hair.base,
  'keybindingLabel.border': alpha(character.hair.base, '40'),
  'keybindingLabel.bottomBorder': alpha(character.hair.base, '60'),
  'keybindingTable.headerBackground': character.hair.base,
  'keybindingTable.rowsBackground': character.hair.base,
  'charts.foreground': character.hair.base,
  'charts.lines': alpha(character.hair.base, '60'),
  'charts.red': character.hair.base,
  'charts.green': character.hair.base,
  'charts.yellow': character.hair.base,
  'charts.blue': character.hair.base,
  'charts.purple': character.hair.base,
  'charts.orange': character.hair.base,
  'menu.background': character.hair.base,
  'menu.foreground': character.hair.base,
  'menu.selectionBackground': alpha(character.hair.base, '30'),
  'menu.selectionForeground': character.hair.base,
  'menu.selectionBorder': alpha(character.hair.base, '50'),
  'menu.separatorBackground': alpha(character.hair.base, '30'),
  'menu.border': alpha(character.hair.base, '60'),
  'commandCenter.foreground': character.hair.base,
  'commandCenter.background': character.hair.base,
  'commandCenter.border': alpha(character.hair.base, '50'),
  'commandCenter.activeBackground': alpha(character.hair.base, '25'),
  'commandCenter.activeForeground': character.hair.base,
  'commandCenter.activeBorder': alpha(character.hair.base, '60'),
  'commandCenter.inactiveForeground': character.hair.base,
  'commandCenter.inactiveBorder': alpha(character.hair.base, '20'),
  'quickInput.background': character.hair.base,
  'quickInput.foreground': character.hair.base,
  'quickInputTitle.background': character.hair.base,
  'quickInputList.focusBackground': alpha(character.hair.base, '30'),
  'quickInputList.focusForeground': character.hair.base,
  'quickInputList.focusIconForeground': character.hair.base,
  'banner.background': character.hair.base,
  'banner.foreground': character.hair.base,
  'banner.iconForeground': character.hair.base,
  'editorError.foreground': character.hair.base,
  'editorError.border': alpha(character.hair.base, '40'),
  'editorError.background': alpha(character.hair.base, '15'),
  'editorWarning.foreground': character.hair.base,
  'editorWarning.border': alpha(character.hair.base, '40'),
  'editorWarning.background': alpha(character.hair.base, '15'),
  'editorInfo.foreground': character.hair.base,
  'editorInfo.border': alpha(character.hair.base, '40'),
  'editorInfo.background': alpha(character.hair.base, '15'),
  'editorHint.foreground': character.hair.base,
  'editorHint.border': alpha(character.hair.base, '40'),
  'problemsErrorIcon.foreground': character.hair.base,
  'problemsWarningIcon.foreground': character.hair.base,
  'problemsInfoIcon.foreground': character.hair.base,
  'editorLightBulb.foreground': character.hair.base,
  'editorLightBulbAutoFix.foreground': character.hair.base,
  'editorLightBulbAi.foreground': character.hair.base,
  'editorInlayHint.background': alpha(character.hair.base, '12'),
  'editorInlayHint.foreground': alpha(character.hair.base, 'DD'),
  'editorInlayHint.typeForeground': alpha(character.hair.base, 'CC'),
  'editorInlayHint.typeBackground': alpha(character.hair.base, '12'),
  'editorInlayHint.parameterForeground': character.hair.base,
  'editorInlayHint.parameterBackground': alpha(character.hair.base, '12'),
  'editorStickyScroll.background': alpha(character.hair.base, 'F0'),
  'editorStickyScroll.border': alpha(character.hair.base, '30'),
  'editorStickyScrollHover.background': alpha(character.hair.base, '10'),
  'notebook.cellBorderColor': alpha(character.hair.base, '30'),
  'notebook.cellEditorBackground': character.hair.base,
  'notebook.cellHoverBackground': alpha(character.hair.base, '10'),
  'notebook.cellInsertionIndicator': character.hair.base,
  'notebook.cellStatusBarItemHoverBackground': alpha(character.hair.base, '20'),
  'notebook.cellToolbarSeparator': alpha(character.hair.base, '30'),
  'notebook.editorBackground': character.hair.base,
  'notebook.focusedCellBorder': character.hair.base,
  'notebook.focusedEditorBorder': alpha(character.hair.base, 'CC'),
  'notebook.inactiveFocusedCellBorder': alpha(character.hair.base, '60'),
  'notebook.outputContainerBackgroundColor': character.hair.base,
  'notebook.outputContainerBorderColor': alpha(character.hair.base, '20'),
  'notebook.selectedCellBackground': alpha(character.hair.base, '15'),
  'notebook.selectedCellBorder': alpha(character.hair.base, '60'),
  'notebook.symbolHighlightBackground': alpha(character.hair.base, '20'),
  'notebookStatusSuccessIcon.foreground': character.hair.base,
  'notebookStatusErrorIcon.foreground': character.hair.base,
  'notebookStatusRunningIcon.foreground': character.hair.base,
  'notebookEditorOverviewRuler.runningCellForeground': character.hair.base,
  'symbolIcon.arrayForeground': character.hair.base,
  'symbolIcon.booleanForeground': character.hair.base,
  'symbolIcon.classForeground': character.hair.base,
  'symbolIcon.colorForeground': character.hair.base,
  'symbolIcon.constantForeground': character.hair.base,
  'symbolIcon.constructorForeground': character.hair.base,
  'symbolIcon.enumeratorForeground': character.hair.base,
  'symbolIcon.enumeratorMemberForeground': character.hair.base,
  'symbolIcon.eventForeground': character.hair.base,
  'symbolIcon.fieldForeground': character.hair.base,
  'symbolIcon.fileForeground': character.hair.base,
  'symbolIcon.folderForeground': character.hair.base,
  'symbolIcon.functionForeground': character.hair.base,
  'symbolIcon.interfaceForeground': character.hair.base,
  'symbolIcon.keyForeground': character.hair.base,
  'symbolIcon.keywordForeground': character.hair.base,
  'symbolIcon.methodForeground': character.hair.base,
  'symbolIcon.moduleForeground': character.hair.base,
  'symbolIcon.namespaceForeground': character.hair.base,
  'symbolIcon.nullForeground': character.hair.base,
  'symbolIcon.numberForeground': character.hair.base,
  'symbolIcon.objectForeground': character.hair.base,
  'symbolIcon.operatorForeground': character.hair.base,
  'symbolIcon.packageForeground': character.hair.base,
  'symbolIcon.propertyForeground': character.hair.base,
  'symbolIcon.referenceForeground': character.hair.base,
  'symbolIcon.snippetForeground': character.hair.base,
  'symbolIcon.stringForeground': character.hair.base,
  'symbolIcon.structForeground': character.hair.base,
  'symbolIcon.textForeground': character.hair.base,
  'symbolIcon.typeParameterForeground': character.hair.base,
  'symbolIcon.unitForeground': character.hair.base,
  'symbolIcon.variableForeground': character.hair.base,
  'inlineChat.background': alpha(character.hair.base, 'F8'),
  'inlineChat.border': alpha(character.hair.base, '60'),
  'inlineChat.shadow': alpha(character.hair.base, '40'),
  'inlineChatInput.background': character.hair.base,
  'inlineChatInput.border': alpha(character.hair.base, '40'),
  'inlineChatInput.focusBorder': character.hair.base,
  'inlineChatInput.placeholderForeground': character.hair.base,
  'inlineChatDiff.inserted': alpha(character.hair.base, '25'),
  'inlineChatDiff.removed': alpha(character.hair.base, '20'),
  'chat.requestBackground': character.hair.base,
  'chat.requestBorder': alpha(character.hair.base, '30'),
  'ports.iconRunningProcessForeground': character.hair.base,
  'profileBadge.background': character.hair.base,
  'profileBadge.foreground': character.hair.base,
  'searchEditor.findMatchBackground': alpha(character.hair.base, '30'),
  'searchEditor.findMatchBorder': alpha(character.hair.base, '80'),
  'searchEditor.textInputBorder': alpha(character.hair.base, '40'),
  'editorUnicodeHighlight.border': alpha(character.hair.base, '80'),
  'editorUnicodeHighlight.background': alpha(character.hair.base, '15'),
  'editorSuggestWidget.background': alpha(character.hair.base, 'F8'),
  'editorSuggestWidget.border': alpha(character.hair.base, 'CC'),
  'editorSuggestWidget.foreground': character.hair.base,
  'editorSuggestWidget.highlightForeground': character.hair.base,
  'editorSuggestWidget.selectedBackground': alpha(character.hair.base, '30'),
  'editorSuggestWidget.selectedForeground': character.hair.base,
  'editorSuggestWidget.selectedIconForeground': character.hair.base,
  'editorSuggestWidget.focusHighlightForeground': character.hair.base,
  'editorMarkerNavigation.background': character.hair.base,
  'editorMarkerNavigationError.background': alpha(character.hair.base, '30'),
  'editorMarkerNavigationWarning.background': alpha(character.hair.base, '30'),
  'editorMarkerNavigationInfo.background': alpha(character.hair.base, '30'),
  'editorMarkerNavigationError.headerBackground': alpha(character.hair.base, '20'),
  'editorMarkerNavigationWarning.headerBackground': alpha(character.hair.base, '20'),
  'editorMarkerNavigationInfo.headerBackground': alpha(character.hair.base, '20'),
  'actionBar.toggledBackground': alpha(character.hair.base, '30'),
  'toolbar.hoverBackground': alpha(character.hair.base, '20'),
  'toolbar.hoverOutline': alpha(character.hair.base, '40'),
  'toolbar.activeBackground': alpha(character.hair.base, '30'),
  'editorActionList.background': character.hair.base,
  'editorActionList.foreground': character.hair.base,
  'editorActionList.focusBackground': alpha(character.hair.base, '30'),
  'editorActionList.focusForeground': character.hair.base,
  'editorCommentsWidget.resolvedBorder': alpha(character.hair.base, '60'),
  'editorCommentsWidget.unresolvedBorder': alpha(character.hair.base, '60'),
  'editorCommentsWidget.rangeBackground': alpha(character.hair.base, '10'),
  'editorCommentsWidget.rangeActiveBackground': alpha(character.hair.base, '20'),
  'editorCommentsWidget.replyInputBackground': character.hair.base,
  'editor.foldBackground': alpha(character.hair.base, '08'),
  'editor.foldPlaceholderForeground': alpha(character.hair.base, 'AA'),
  'editor.snippetTabstopHighlightBackground': alpha(character.hair.base, '18'),
  'editor.snippetTabstopHighlightBorder': alpha(character.hair.base, '50'),
  'editor.snippetFinalTabstopHighlightBackground': alpha(character.hair.base, '20'),
  'editor.snippetFinalTabstopHighlightBorder': alpha(character.hair.base, '60'),
  'editor.symbolHighlightBackground': alpha(character.hair.base, '15'),
  'editor.symbolHighlightBorder': alpha(character.hair.base, '40'),
  'editor.hoverHighlightBackground': alpha(character.hair.base, '12'),
  'scmGraph.foreground1': character.hair.base,
  'scmGraph.foreground2': character.hair.base,
  'scmGraph.foreground3': character.hair.base,
  'scmGraph.foreground4': character.hair.base,
  'scmGraph.foreground5': character.hair.base,
  'chat.slashCommandBackground': alpha(character.hair.base, '20'),
  'chat.slashCommandForeground': character.hair.base,
  'chat.avatarBackground': alpha(character.hair.base, '30'),
  'chat.avatarForeground': character.hair.base,
  'interactive.activeCodeBorder': alpha(character.hair.base, '60'),
  'interactive.inactiveCodeBorder': alpha(character.hair.base, '30'),
  'terminalSymbolIcon.aliasForeground': character.hair.base,
  'terminalSymbolIcon.branchForeground': character.hair.base,
  'terminalSymbolIcon.commitForeground': character.hair.base,
  'terminalSymbolIcon.flagForeground': character.hair.base,
  'terminalSymbolIcon.optionForeground': character.hair.base,
  'terminalSymbolIcon.optionValueForeground': character.hair.base,
  'terminalSymbolIcon.methodForeground': character.hair.base,
  'terminalSymbolIcon.argumentForeground': character.hair.base,
  'terminalSymbolIcon.inlineSuggestionForeground': character.hair.base,
  'terminalSymbolIcon.fileForeground': character.hair.base,
  'terminalSymbolIcon.folderForeground': character.hair.base,
  'terminalSymbolIcon.pullRequestDoneForeground': character.hair.base,
  'terminalSymbolIcon.pullRequestForeground': character.hair.base,
  'terminalSymbolIcon.remoteForeground': character.hair.base,
  'terminalSymbolIcon.stashForeground': character.hair.base,
  'terminalSymbolIcon.symbolText': character.hair.base,
  'terminalSymbolIcon.symbolicLinkFileForeground': character.hair.base,
  'terminalSymbolIcon.symbolicLinkFolderForeground': character.hair.base,
  'terminalSymbolIcon.tagForeground': character.hair.base,
  'inlineEdit.gutterIndicator.primaryBorder': character.hair.base,
  'inlineEdit.gutterIndicator.primaryForeground': character.hair.base,
  'inlineEdit.gutterIndicator.primaryBackground': alpha(character.hair.base, '20'),
  'inlineEdit.gutterIndicator.secondaryBorder': alpha(character.hair.base, '60'),
  'inlineEdit.gutterIndicator.secondaryForeground': character.hair.base,
  'inlineEdit.gutterIndicator.secondaryBackground': alpha(character.hair.base, '15'),
  'inlineEdit.gutterIndicator.successfulBorder': character.hair.base,
  'inlineEdit.gutterIndicator.successfulForeground': character.hair.base,
  'inlineEdit.gutterIndicator.successfulBackground': alpha(character.hair.base, '20'),
  'inlineEdit.gutterIndicator.background': alpha(character.hair.base, '10'),
  'inlineEdit.originalBackground': alpha(character.hair.base, '10'),
  'inlineEdit.modifiedBackground': alpha(character.hair.base, '15'),
  'inlineEdit.originalChangedLineBackground': alpha(character.hair.base, '15'),
  'inlineEdit.originalChangedTextBackground': alpha(character.hair.base, '25'),
  'inlineEdit.modifiedChangedLineBackground': alpha(character.hair.base, '15'),
  'inlineEdit.modifiedChangedTextBackground': alpha(character.hair.base, '25'),
  'inlineEdit.originalBorder': alpha(character.hair.base, '40'),
  'inlineEdit.modifiedBorder': alpha(character.hair.base, '50'),
  'inlineEdit.tabWillAcceptModifiedBorder': character.hair.base,
  'inlineEdit.tabWillAcceptOriginalBorder': alpha(character.hair.base, '60'),
  'testing.iconErrored.retired': alpha(character.hair.base, '60'),
  'testing.iconFailed.retired': alpha(character.hair.base, '60'),
  'testing.iconPassed.retired': alpha(character.hair.base, '60'),
  'testing.iconQueued.retired': alpha(character.hair.base, '60'),
  'testing.iconUnset.retired': alpha(character.hair.base, '60'),
  'testing.iconSkipped.retired': alpha(character.hair.base, '60'),
  'testing.message.error.badgeBackground': alpha(character.hair.base, '25'),
  'testing.message.error.badgeBorder': character.hair.base,
  'testing.message.error.badgeForeground': character.hair.base,
  'testing.messagePeekBorder': character.hair.base,
  'testing.messagePeekHeaderBackground': character.hair.base,
  'testing.coveredBackground': alpha(character.hair.base, '12'),
  'testing.coveredBorder': alpha(character.hair.base, '40'),
  'testing.coveredGutterBackground': alpha(character.hair.base, '30'),
  'testing.uncoveredBranchBackground': alpha(character.hair.base, '20'),
  'testing.uncoveredBackground': alpha(character.hair.base, '12'),
  'testing.uncoveredBorder': alpha(character.hair.base, '40'),
  'testing.uncoveredGutterBackground': alpha(character.hair.base, '30'),
  'testing.coverCountBadgeBackground': alpha(character.hair.base, '25'),
  'testing.coverCountBadgeForeground': character.hair.base,
  'scmGraph.historyItemHoverAdditionsForeground': character.hair.base,
  'scmGraph.historyItemHoverDeletionsForeground': character.hair.base,
  'scmGraph.historyItemRefColor': character.hair.base,
  'scmGraph.historyItemRemoteRefColor': character.hair.base,
  'scmGraph.historyItemBaseRefColor': character.hair.base,
  'chat.editedFileForeground': character.hair.base,
  'chat.linesAddedForeground': character.hair.base,
  'chat.linesRemovedForeground': character.hair.base,
  'chat.requestCodeBorder': alpha(character.hair.base, '40'),
  'chat.requestBubbleBackground': alpha(character.hair.base, '15'),
  'chat.requestBubbleHoverBackground': alpha(character.hair.base, '25'),
  'chat.checkpointSeparator': alpha(character.hair.base, '30'),
  'chatManagement.sashBorder': alpha(character.hair.base, '40'),
  'tab.lastPinnedBorder': alpha(character.hair.base, '60'),
  'tab.activeModifiedBorder': character.hair.base,
  'tab.inactiveModifiedBorder': alpha(character.hair.base, '60'),
  'tab.unfocusedActiveModifiedBorder': alpha(character.hair.base, '80'),
  'tab.unfocusedInactiveModifiedBorder': alpha(character.hair.base, '40'),
  'tab.dragAndDropBorder': alpha(character.hair.base, '60'),
  'tab.selectedBackground': character.hair.base,
  'tab.selectedForeground': character.hair.base,
  'tab.selectedBorderTop': character.hair.base,
  'checkbox.selectBackground': alpha(character.hair.base, '30'),
  'checkbox.selectBorder': character.hair.base,
  'checkbox.disabled.background': alpha(character.hair.base, '20'),
  'checkbox.disabled.foreground': character.hair.base,
  'radio.activeForeground': character.hair.base,
  'radio.activeBackground': character.hair.base,
  'radio.activeBorder': character.hair.base,
  'radio.inactiveForeground': character.hair.base,
  'radio.inactiveBackground': character.hair.base,
  'radio.inactiveBorder': alpha(character.hair.base, '40'),
  'radio.inactiveHoverBackground': alpha(character.hair.base, '15'),
  'editorOverviewRuler.modifiedForeground': alpha(character.hair.base, '90'),
  'editorOverviewRuler.addedForeground': alpha(character.hair.base, '90'),
  'editorOverviewRuler.deletedForeground': alpha(character.hair.base, '90'),
  'editorOverviewRuler.commentForeground': alpha(character.hair.base, '60'),
  'editorOverviewRuler.commentUnresolvedForeground': alpha(character.hair.base, '60'),
  'editorOverviewRuler.inlineChatInserted': alpha(character.hair.base, '70'),
  'editorOverviewRuler.inlineChatRemoved': alpha(character.hair.base, '70'),
  'editorGutter.modifiedSecondaryBackground': alpha(character.hair.base, '50'),
  'editorGutter.addedSecondaryBackground': alpha(character.hair.base, '50'),
  'editorGutter.deletedSecondaryBackground': alpha(character.hair.base, '50'),
  'editorGutter.commentRangeForeground': alpha(character.hair.base, '40'),
  'editorGutter.commentGlyphForeground': character.hair.base,
  'editorGutter.commentUnresolvedGlyphForeground': character.hair.base,
  'merge.currentHeaderBackground': alpha(character.hair.base, '40'),
  'merge.currentContentBackground': alpha(character.hair.base, '15'),
  'merge.incomingHeaderBackground': alpha(character.hair.base, '40'),
  'merge.incomingContentBackground': alpha(character.hair.base, '15'),
  'merge.border': alpha(character.hair.base, '70'),
  'merge.commonContentBackground': alpha(character.hair.base, '15'),
  'merge.commonHeaderBackground': alpha(character.hair.base, '30'),
  'mergeEditor.changeBase.background': alpha(character.hair.base, '15'),
  'mergeEditor.changeBase.word.background': alpha(character.hair.base, '30'),
  'mergeEditor.conflict.input1.background': alpha(character.hair.base, '15'),
  'mergeEditor.conflict.input2.background': alpha(character.hair.base, '15'),
  'panelTitleBadge.background': character.hair.base,
  'panelTitleBadge.foreground': character.hair.base,
  'panelStickyScroll.background': character.hair.base,
  'panelStickyScroll.border': alpha(character.hair.base, '20'),
  'panelStickyScroll.shadow': alpha(character.hair.base, '50'),
  'outputView.background': character.hair.base,
  'outputViewStickyScroll.background': character.hair.base,
  'activityWarningBadge.foreground': character.hair.base,
  'activityWarningBadge.background': character.hair.base,
  'activityErrorBadge.foreground': character.hair.base,
  'activityErrorBadge.background': character.hair.base,
  'commandCenter.debuggingBackground': alpha(character.hair.base, '25'),
  'list.dropBackground': alpha(character.hair.base, '20'),
  'list.dropBetweenBackground': alpha(character.hair.base, '40'),
  'list.focusAndSelectionOutline': alpha(character.hair.base, '60'),
  'list.inactiveSelectionIconForeground': character.hair.base,
  'list.inactiveFocusBackground': alpha(character.hair.base, '15'),
  'list.inactiveFocusOutline': alpha(character.hair.base, '30'),
  'list.filterMatchBackground': alpha(character.hair.base, '25'),
  'list.filterMatchBorder': alpha(character.hair.base, '50'),
  'listFilterWidget.shadow': alpha(character.hair.base, '50'),
  'tree.inactiveIndentGuidesStroke': alpha(character.hair.base, '15'),
  'tree.tableOddRowsBackground': alpha(character.hair.base, '05'),
  'badge.foreground': character.hair.base,
  'badge.background': character.hair.base,
  'progressBar.background': character.hair.base,
  'editor.placeholder.foreground': alpha(character.hair.base, '60'),
  'editor.inactiveSelectionBackground': alpha(character.hair.base, '20'),
  'editor.wordHighlightTextBackground': alpha(character.hair.base, '15'),
  'editor.wordHighlightTextBorder': alpha(character.hair.base, '35'),
  'editor.findMatchForeground': character.hair.base,
  'editor.findMatchHighlightForeground': character.hair.base,
  'editor.findRangeHighlightBorder': alpha(character.hair.base, '40'),
  'search.resultsInfoForeground': character.hair.base,
  'editorStickyScroll.shadow': alpha(character.hair.base, '30'),
  'editorStickyScrollGutter.background': alpha(character.hair.base, 'F0'),
  'commentsView.resolvedIcon': character.hair.base,
  'commentsView.unresolvedIcon': character.hair.base,
  'terminal.hoverHighlightBackground': alpha(character.hair.base, '20'),
  'terminal.initialHintForeground': alpha(character.hair.base, '80'),
  'terminal.selectionForeground': character.hair.base,
  'terminal.dropBackground': alpha(character.hair.base, '20'),
  'terminalCommandGuide.foreground': alpha(character.hair.base, '40'),
  'terminalOverviewRuler.border': alpha(character.hair.base, '30'),
  'terminalStickyScroll.background': character.hair.base,
  'terminalStickyScroll.border': alpha(character.hair.base, '20'),
  'terminalStickyScrollHover.background': alpha(character.hair.base, '15'),
  'sideBarTitle.background': character.hair.base,
  'sideBarTitle.border': alpha(character.hair.base, '15'),
  'sideBarActivityBarTop.border': alpha(character.hair.base, '15'),
  'peekViewEditorStickyScroll.background': character.hair.base,
  'peekViewEditorStickyScrollGutter.background': character.hair.base,
  'debugExceptionWidget.background': alpha(character.hair.base, '20'),
  'debugExceptionWidget.border': character.hair.base,
  'editor.inlineValuesForeground': character.hair.base,
  'editor.inlineValuesBackground': alpha(character.hair.base, '15'),
  'debugTokenExpression.type': character.hair.base,
  'minimap.chatEditHighlight': alpha(character.hair.base, '60'),
  'editorMinimap.inlineChatInserted': alpha(character.hair.base, '50'),
  'diffEditor.unchangedRegionShadow': alpha(character.hair.base, '30'),
  'diffEditor.move.border': alpha(character.hair.base, '60'),
  'diffEditor.moveActive.border': character.hair.base,
  'sideBySideEditor.horizontalBorder': alpha(character.hair.base, '25'),
  'sideBySideEditor.verticalBorder': alpha(character.hair.base, '25'),
  'editorPane.background': character.hair.base,
  'editorGroup.dropIntoPromptForeground': character.hair.base,
  'editorGroup.dropIntoPromptBackground': alpha(character.hair.base, 'F0'),
  'editorGroup.dropIntoPromptBorder': alpha(character.hair.base, '50'),
  'editorGroup.emptyBackground': character.hair.base,
  'editorGroup.focusedEmptyBorder': alpha(character.hair.base, '40'),
  'git.blame.editorDecorationForeground': alpha(character.hair.base, '60'),
  'walkthrough.stepTitle.foreground': character.hair.base,
  'settings.settingsHeaderHoverForeground': character.hair.base,
  'profiles.sashBorder': alpha(character.hair.base, '30'),
  'simpleFindWidget.sashBorder': alpha(character.hair.base, '40'),
  'contrastActiveBorder': alpha(character.hair.base, 'CC'),
  'contrastBorder': alpha(character.hair.base, '60'),
  'widget.border': alpha(character.hair.base, '40'),
  'window.activeBorder': alpha(character.hair.base, '60'),
  'window.inactiveBorder': alpha(character.hair.base, '30'),
  'textPreformat.background': alpha(character.hair.base, '80'),
  'textPreformat.border': alpha(character.hair.base, '30'),
  'button.separator': alpha(character.hair.base, '60'),
  'scrollbar.background': alpha(character.hair.base, '00'),
  'list.focusHighlightForeground': character.hair.base,
  'activityBar.activeFocusBorder': character.hair.base,
  'activityBar.dropBorder': alpha(character.hair.base, '60'),
  'activityBarTop.activeBackground': alpha(character.hair.base, '20'),
  'activityBarTop.background': character.hair.base,
  'activityBarTop.dropBorder': alpha(character.hair.base, '60'),
  'editorGroupHeader.border': alpha(character.hair.base, '20'),
  'tab.unfocusedActiveBorder': alpha(character.hair.base, '40'),
  'tab.unfocusedHoverBackground': alpha(character.hair.base, '10'),
  'tab.unfocusedHoverBorder': alpha(character.hair.base, '30'),
  'tab.unfocusedHoverForeground': character.hair.base,
  'editor.compositionBorder': alpha(character.hair.base, '60'),
  'editor.findRangeHighlightBackground': alpha(character.hair.base, '15'),
  'editor.inactiveLineHighlightBackground': alpha(character.hair.base, '08'),
  'editor.selectionForeground': character.hair.base,
  'editorIndentGuide.activeBackground': alpha(character.hair.base, '50'),
  'editorIndentGuide.background': alpha(character.hair.base, '20'),
  'editorOverviewRuler.background': character.hair.base,
  'editorOverviewRuler.border': alpha(character.hair.base, '20'),
  'editorOverviewRuler.commentDraftForeground': alpha(character.hair.base, '50'),
  'editorOverviewRuler.commonContentForeground': alpha(character.hair.base, '60'),
  'editorOverviewRuler.currentContentForeground': alpha(character.hair.base, '80'),
  'editorOverviewRuler.incomingContentForeground': alpha(character.hair.base, '80'),
  'editorOverviewRuler.rangeHighlightForeground': alpha(character.hair.base, '60'),
  'editorUnnecessaryCode.border': alpha(character.hair.base, '40'),
  'editorGutter.background': character.hair.base,
  'editorGutter.commentDraftGlyphForeground': alpha(character.hair.base, '80'),
  'editorGutter.itemBackground': alpha(character.hair.base, '15'),
  'editorGutter.itemGlyphForeground': character.hair.base,
  'diffEditor.insertedTextBorder': alpha(character.hair.base, '50'),
  'diffEditor.removedTextBorder': alpha(character.hair.base, '50'),
  'inlineChat.foreground': character.hair.base,
  'editorSuggestWidgetStatus.foreground': character.hair.base,
  'panelTitle.border': alpha(character.hair.base, '30'),
  'statusBar.focusBorder': alpha(character.hair.base, 'DD'),
  'statusBarItem.errorHoverForeground': character.hair.base,
  'statusBarItem.offlineBackground': character.hair.base,
  'statusBarItem.offlineForeground': character.hair.base,
  'statusBarItem.offlineHoverBackground': alpha(character.hair.base, 'CC'),
  'statusBarItem.offlineHoverForeground': character.hair.base,
  'statusBarItem.remoteHoverForeground': character.hair.base,
  'statusBarItem.warningHoverForeground': character.hair.base,
  'extensionButton.background': character.hair.base,
  'extensionButton.foreground': character.hair.base,
  'extensionButton.hoverBackground': character.hair.base,
  'extensionIcon.privateForeground': character.hair.base,
  'mcpIcon.starForeground': character.hair.base,
  'scmGraph.historyItemHoverLabelForeground': character.hair.base,
  'chart.axis': alpha(character.hair.base, '80'),
  'chart.guide': alpha(character.hair.base, '30'),
  'chart.line': character.hair.base,
  'gauge.background': character.hair.base,
  'gauge.border': alpha(character.hair.base, '40'),
  'gauge.errorBackground': alpha(character.hair.base, '30'),
  'gauge.errorForeground': character.hair.base,
  'gauge.foreground': character.hair.base,
  'gauge.warningBackground': alpha(character.hair.base, '30'),
  'gauge.warningForeground': character.hair.base,
  'markdownAlert.caution.foreground': character.hair.base,
  'markdownAlert.important.foreground': character.hair.base,
  'markdownAlert.note.foreground': character.hair.base,
  'markdownAlert.tip.foreground': character.hair.base,
  'markdownAlert.warning.foreground': character.hair.base,
  'agentSessionReadIndicator.foreground': character.hair.base,
  'agentSessionSelectedBadge.border': character.hair.base,
  'agentSessionSelectedUnfocusedBadge.border': alpha(character.hair.base, '60'),
  'notebook.focusedCellBackground': alpha(character.hair.base, '10'),
  'notebook.inactiveSelectedCellBorder': alpha(character.hair.base, '40'),
  'notebookScrollbarSlider.activeBackground': alpha(character.hair.base, '80'),
  'notebookScrollbarSlider.background': alpha(character.hair.base, '40'),
  'notebookScrollbarSlider.hoverBackground': alpha(character.hair.base, '60'),
  'outputsNotebook.border': alpha(character.hair.base, '30'),
} as const;
export type WorkbenchColors = typeof workbenchColors;
