-- Hatsune Miku Theme — Neovim
-- Generated — do not edit

if vim.g.colors_name then
  vim.cmd("hi clear")
end

vim.o.termguicolors = true
vim.o.background = "dark"
vim.g.colors_name = "hatsune-miku-dark"

local groups = {
  ["Normal"] = { fg = "#DEE8F2", bg = "#1A1F24" },
  ["NormalFloat"] = { fg = "#DEE8F2", bg = "#2A3035" },
  ["NormalNC"] = { fg = "#DEE8F2", bg = "#1A1F24" },
  ["Cursor"] = { fg = "#1A1F24", bg = "#FF8CD9" },
  ["CursorLine"] = { bg = "#23282D" },
  ["CursorColumn"] = { bg = "#23282D" },
  ["CursorLineNr"] = { fg = "#39C5BB", bold = true },
  ["ColorColumn"] = { bg = "#23282D" },
  ["LineNr"] = { fg = "#89A0A1" },
  ["LineNrAbove"] = { link = "LineNr" },
  ["LineNrBelow"] = { link = "LineNr" },
  ["SignColumn"] = { fg = "#89A0A1", bg = "#1A1F24" },
  ["FoldColumn"] = { fg = "#89A0A1", bg = "#1A1F24" },
  ["Folded"] = { fg = "#BDD7D9", bg = "#23282D" },
  ["VertSplit"] = { fg = "#39C5BB" },
  ["WinSeparator"] = { fg = "#39C5BB" },
  ["StatusLine"] = { fg = "#DEE8F2", bg = "#23282D" },
  ["StatusLineNC"] = { fg = "#BDD7D9", bg = "#23282D" },
  ["TabLine"] = { fg = "#BDD7D9", bg = "#23282D" },
  ["TabLineFill"] = { bg = "#23282D" },
  ["TabLineSel"] = { fg = "#DEE8F2", bg = "#1A1F24", bold = true },
  ["WinBar"] = { fg = "#DEE8F2", bg = "#23282D" },
  ["WinBarNC"] = { fg = "#BDD7D9", bg = "#23282D" },
  ["Pmenu"] = { fg = "#DEE8F2", bg = "#2A3035" },
  ["PmenuSel"] = { fg = "#DEE8F2", bg = "#39C5BB40" },
  ["PmenuSbar"] = { bg = "#23282D" },
  ["PmenuThumb"] = { bg = "#39C5BB" },
  ["PmenuMatch"] = { fg = "#39C5BB" },
  ["PmenuMatchSel"] = { fg = "#39C5BB", bg = "#39C5BB40" },
  ["FloatBorder"] = { fg = "#39C5BB", bg = "#2A3035" },
  ["FloatTitle"] = { fg = "#39C5BB", bg = "#2A3035", bold = true },
  ["Search"] = { fg = "#1A1F24", bg = "#FFC39B" },
  ["IncSearch"] = { fg = "#1A1F24", bg = "#39C5BB" },
  ["CurSearch"] = { fg = "#1A1F24", bg = "#FF8CD9" },
  ["Substitute"] = { fg = "#1A1F24", bg = "#F0CD7B" },
  ["Visual"] = { bg = "#39C5BB40" },
  ["VisualNOS"] = { bg = "#39C5BB40" },
  ["MatchParen"] = { fg = "#FF8CD9", bold = true },
  ["DiffAdd"] = { bg = "#8AF9B425" },
  ["DiffChange"] = { bg = "#F0CD7B25" },
  ["DiffDelete"] = { bg = "#FA91F925" },
  ["DiffText"] = { bg = "#F0CD7B40" },
  ["Added"] = { fg = "#8AF9B4" },
  ["Changed"] = { fg = "#F0CD7B" },
  ["Removed"] = { fg = "#FA91F9" },
  ["ErrorMsg"] = { fg = "#FF8DED" },
  ["WarningMsg"] = { fg = "#F0CD7B" },
  ["MoreMsg"] = { fg = "#39C5BB" },
  ["Question"] = { fg = "#39C5BB" },
  ["ModeMsg"] = { fg = "#BDD7D9", bold = true },
  ["MsgArea"] = { fg = "#DEE8F2" },
  ["Directory"] = { fg = "#39C5BB" },
  ["Title"] = { fg = "#39C5BB", bold = true },
  ["NonText"] = { fg = "#89A0A1" },
  ["EndOfBuffer"] = { fg = "#89A0A1" },
  ["Whitespace"] = { fg = "#89A0A1" },
  ["SpecialKey"] = { fg = "#89A0A1" },
  ["Conceal"] = { fg = "#BDD7D9" },
  ["WildMenu"] = { fg = "#1A1F24", bg = "#39C5BB" },
  ["QuickFixLine"] = { bg = "#39C5BB40" },
  ["SpellBad"] = { sp = "#FF8DED", undercurl = true },
  ["SpellCap"] = { sp = "#F0CD7B", undercurl = true },
  ["SpellRare"] = { sp = "#C1D5FF", undercurl = true },
  ["SpellLocal"] = { sp = "#C1D5FF", undercurl = true },
  ["Comment"] = { fg = "#8DC6B6", italic = true },
  ["Constant"] = { fg = "#96E0FF" },
  ["String"] = { fg = "#BCE498" },
  ["Character"] = { fg = "#BCE498" },
  ["Number"] = { fg = "#A8DEFF" },
  ["Boolean"] = { fg = "#A8DEFF" },
  ["Float"] = { fg = "#A8DEFF" },
  ["Identifier"] = { fg = "#27F1FC" },
  ["Function"] = { fg = "#FFC39B" },
  ["Statement"] = { fg = "#66F3D3" },
  ["Conditional"] = { fg = "#66F3D3" },
  ["Repeat"] = { fg = "#66F3D3" },
  ["Label"] = { fg = "#66F3D3" },
  ["Operator"] = { fg = "#FFB7FF" },
  ["Keyword"] = { fg = "#66F3D3" },
  ["Exception"] = { fg = "#66F3D3" },
  ["PreProc"] = { fg = "#F5C1FF" },
  ["Include"] = { fg = "#66F3D3" },
  ["Define"] = { fg = "#F5C1FF" },
  ["Macro"] = { fg = "#F5C1FF" },
  ["PreCondit"] = { fg = "#F5C1FF" },
  ["Type"] = { fg = "#C9D0FF" },
  ["StorageClass"] = { fg = "#66F3D3" },
  ["Structure"] = { fg = "#E4D28E" },
  ["Typedef"] = { fg = "#C9D0FF" },
  ["Special"] = { fg = "#FFBECD" },
  ["SpecialChar"] = { fg = "#FFBECD" },
  ["Tag"] = { fg = "#FAC8AA" },
  ["Delimiter"] = { fg = "#7AD7C0" },
  ["SpecialComment"] = { fg = "#85BCAD", italic = true },
  ["Debug"] = { fg = "#F0CD7B" },
  ["Underlined"] = { fg = "#84CCC8", underline = true },
  ["Error"] = { fg = "#FF8DED" },
  ["Todo"] = { fg = "#39C5BB", bold = true },
  ["@keyword"] = { fg = "#66F3D3" },
  ["@keyword.coroutine"] = { fg = "#66F3D3" },
  ["@keyword.function"] = { fg = "#66F3D3" },
  ["@keyword.operator"] = { fg = "#FFB7FF" },
  ["@keyword.import"] = { fg = "#66F3D3" },
  ["@keyword.type"] = { fg = "#66F3D3" },
  ["@keyword.modifier"] = { fg = "#66F3D3" },
  ["@keyword.repeat"] = { fg = "#66F3D3" },
  ["@keyword.return"] = { fg = "#66F3D3" },
  ["@keyword.debug"] = { fg = "#66F3D3" },
  ["@keyword.exception"] = { fg = "#66F3D3" },
  ["@keyword.conditional"] = { fg = "#66F3D3" },
  ["@keyword.conditional.ternary"] = { fg = "#FFB7FF" },
  ["@keyword.directive"] = { fg = "#F5C1FF" },
  ["@keyword.directive.define"] = { fg = "#F5C1FF" },
  ["@variable"] = { fg = "#27F1FC" },
  ["@variable.builtin"] = { fg = "#66F3D3", italic = true },
  ["@variable.parameter"] = { fg = "#FFBECD" },
  ["@variable.parameter.builtin"] = { fg = "#FFBECD", italic = true },
  ["@variable.member"] = { fg = "#FFBECD" },
  ["@constant"] = { fg = "#96E0FF" },
  ["@constant.builtin"] = { fg = "#96E0FF" },
  ["@constant.macro"] = { fg = "#F5C1FF" },
  ["@module"] = { fg = "#C9D0FF" },
  ["@module.builtin"] = { fg = "#C9D0FF", italic = true },
  ["@label"] = { fg = "#66F3D3" },
  ["@string"] = { fg = "#BCE498" },
  ["@string.documentation"] = { fg = "#85BCAD" },
  ["@string.regexp"] = { fg = "#B7E888" },
  ["@string.escape"] = { fg = "#FFBECD" },
  ["@string.special"] = { fg = "#BCE498" },
  ["@string.special.symbol"] = { fg = "#96E0FF" },
  ["@string.special.url"] = { fg = "#84CCC8", underline = true },
  ["@string.special.path"] = { fg = "#BCE498" },
  ["@character"] = { fg = "#BCE498" },
  ["@character.special"] = { fg = "#FFBECD" },
  ["@number"] = { fg = "#A8DEFF" },
  ["@number.float"] = { fg = "#A8DEFF" },
  ["@boolean"] = { fg = "#A8DEFF" },
  ["@type"] = { fg = "#C9D0FF" },
  ["@type.builtin"] = { fg = "#C9D0FF" },
  ["@type.definition"] = { fg = "#CDD3FF" },
  ["@attribute"] = { fg = "#F5C1FF" },
  ["@attribute.builtin"] = { fg = "#F5C1FF" },
  ["@property"] = { fg = "#FFBECD" },
  ["@function"] = { fg = "#FFC39B" },
  ["@function.builtin"] = { fg = "#FFC492" },
  ["@function.call"] = { fg = "#FFC39B" },
  ["@function.macro"] = { fg = "#F5C1FF" },
  ["@function.method"] = { fg = "#FFC39B" },
  ["@function.method.call"] = { fg = "#FFC39B" },
  ["@constructor"] = { fg = "#E9D27B" },
  ["@operator"] = { fg = "#FFB7FF" },
  ["@punctuation.delimiter"] = { fg = "#7AD7C0" },
  ["@punctuation.bracket"] = { fg = "#7AD7C0" },
  ["@punctuation.special"] = { fg = "#7AD7C0" },
  ["@comment"] = { fg = "#8DC6B6", italic = true },
  ["@comment.documentation"] = { fg = "#85BCAD", italic = true },
  ["@comment.error"] = { fg = "#FF8DED" },
  ["@comment.warning"] = { fg = "#F0CD7B" },
  ["@comment.todo"] = { fg = "#39C5BB", bold = true },
  ["@comment.note"] = { fg = "#C1D5FF" },
  ["@markup.strong"] = { bold = true },
  ["@markup.italic"] = { italic = true },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.underline"] = { underline = true },
  ["@markup.heading"] = { fg = "#FFC492", bold = true },
  ["@markup.quote"] = { fg = "#69EBF3", italic = true },
  ["@markup.math"] = { fg = "#A8DEFF" },
  ["@markup.link"] = { fg = "#84CCC8" },
  ["@markup.link.label"] = { fg = "#84CCC8" },
  ["@markup.link.url"] = { fg = "#C9D0FF", underline = true },
  ["@markup.raw"] = { fg = "#27F1FC" },
  ["@markup.raw.block"] = { fg = "#27F1FC" },
  ["@markup.list"] = { fg = "#7AD7C0" },
  ["@markup.list.checked"] = { fg = "#68FCCD" },
  ["@markup.list.unchecked"] = { fg = "#BDD7D9" },
  ["@diff.plus"] = { fg = "#8AF9B4" },
  ["@diff.minus"] = { fg = "#FA91F9" },
  ["@diff.delta"] = { fg = "#F0CD7B" },
  ["@tag"] = { fg = "#FAC8AA" },
  ["@tag.builtin"] = { fg = "#FAC8AA" },
  ["@tag.attribute"] = { fg = "#FFBECD" },
  ["@tag.delimiter"] = { fg = "#7AD7C0" },
  ["@lsp.type.namespace"] = { fg = "#C9D0FF" },
  ["@lsp.type.type"] = { fg = "#C9D0FF" },
  ["@lsp.type.class"] = { fg = "#E9D27B" },
  ["@lsp.type.enum"] = { fg = "#E9D27B" },
  ["@lsp.type.interface"] = { fg = "#8DF0B1" },
  ["@lsp.type.struct"] = { fg = "#E4D28E" },
  ["@lsp.type.typeParameter"] = { fg = "#CDD3FF" },
  ["@lsp.type.parameter"] = { fg = "#FFBECD" },
  ["@lsp.type.variable"] = { fg = "#27F1FC" },
  ["@lsp.type.property"] = { fg = "#FFBECD" },
  ["@lsp.type.enumMember"] = { fg = "#96E0FF" },
  ["@lsp.type.function"] = { fg = "#FFC39B" },
  ["@lsp.type.method"] = { fg = "#FFC39B" },
  ["@lsp.type.macro"] = { fg = "#F5C1FF" },
  ["@lsp.type.keyword"] = { fg = "#66F3D3" },
  ["@lsp.type.modifier"] = { fg = "#66F3D3" },
  ["@lsp.type.comment"] = { fg = "#8DC6B6", italic = true },
  ["@lsp.type.string"] = { fg = "#BCE498" },
  ["@lsp.type.number"] = { fg = "#A8DEFF" },
  ["@lsp.type.regexp"] = { fg = "#B7E888" },
  ["@lsp.type.operator"] = { fg = "#FFB7FF" },
  ["@lsp.type.decorator"] = { fg = "#F5C1FF" },
  ["@lsp.mod.deprecated"] = { strikethrough = true },
  ["LspReferenceText"] = { bg = "#39C5BB25" },
  ["LspReferenceRead"] = { bg = "#39C5BB25" },
  ["LspReferenceWrite"] = { bg = "#39C5BB40" },
  ["LspInlayHint"] = { fg = "#89A0A1", italic = true },
  ["LspCodeLens"] = { fg = "#89A0A1" },
  ["LspSignatureActiveParameter"] = { fg = "#39C5BB", bold = true },
  ["DiagnosticError"] = { fg = "#FF8DED" },
  ["DiagnosticWarn"] = { fg = "#F0CD7B" },
  ["DiagnosticInfo"] = { fg = "#C1D5FF" },
  ["DiagnosticHint"] = { fg = "#39C5BB" },
  ["DiagnosticOk"] = { fg = "#68FCCD" },
  ["DiagnosticVirtualTextError"] = { fg = "#FF8DED", bg = "#FF8DED15" },
  ["DiagnosticVirtualTextWarn"] = { fg = "#F0CD7B", bg = "#F0CD7B15" },
  ["DiagnosticVirtualTextInfo"] = { fg = "#C1D5FF", bg = "#C1D5FF15" },
  ["DiagnosticVirtualTextHint"] = { fg = "#39C5BB", bg = "#39C5BB15" },
  ["DiagnosticVirtualTextOk"] = { fg = "#68FCCD", bg = "#68FCCD15" },
  ["DiagnosticUnderlineError"] = { sp = "#FF8DED", undercurl = true },
  ["DiagnosticUnderlineWarn"] = { sp = "#F0CD7B", undercurl = true },
  ["DiagnosticUnderlineInfo"] = { sp = "#C1D5FF", undercurl = true },
  ["DiagnosticUnderlineHint"] = { sp = "#39C5BB", undercurl = true },
  ["DiagnosticUnderlineOk"] = { sp = "#68FCCD", undercurl = true },
  ["DiagnosticDeprecated"] = { strikethrough = true },
  ["GitSignsAdd"] = { fg = "#8AF9B4" },
  ["GitSignsChange"] = { fg = "#F0CD7B" },
  ["GitSignsDelete"] = { fg = "#FA91F9" },
  ["TelescopeNormal"] = { fg = "#DEE8F2", bg = "#2A3035" },
  ["TelescopeBorder"] = { fg = "#39C5BB", bg = "#2A3035" },
  ["TelescopeTitle"] = { fg = "#39C5BB", bold = true },
  ["TelescopeSelection"] = { bg = "#39C5BB40" },
  ["TelescopeSelectionCaret"] = { fg = "#FF8CD9" },
  ["TelescopeMatching"] = { fg = "#39C5BB", bold = true },
  ["TelescopePromptPrefix"] = { fg = "#39C5BB" },
}

for group, hl in pairs(groups) do
  vim.api.nvim_set_hl(0, group, hl)
end

-- Terminal ANSI colors
vim.g.terminal_color_0 = "#909BA7"
vim.g.terminal_color_1 = "#FF8FC4"
vim.g.terminal_color_2 = "#51FEA1"
vim.g.terminal_color_3 = "#FFE8C7"
vim.g.terminal_color_4 = "#AEB4FA"
vim.g.terminal_color_5 = "#FFC4FA"
vim.g.terminal_color_6 = "#76FFE6"
vim.g.terminal_color_7 = "#F3BEC4"
vim.g.terminal_color_8 = "#9AB2B3"
vim.g.terminal_color_9 = "#FF8DD2"
vim.g.terminal_color_10 = "#62FFB1"
vim.g.terminal_color_11 = "#FFE2B7"
vim.g.terminal_color_12 = "#AAB0FF"
vim.g.terminal_color_13 = "#FFD6FF"
vim.g.terminal_color_14 = "#4BFFF9"
vim.g.terminal_color_15 = "#8CE5EA"
