-- Hatsune Miku Theme — Neovim
-- Generated — do not edit

if vim.g.colors_name then
  vim.cmd("hi clear")
end

vim.o.termguicolors = true
vim.o.background = "light"
vim.g.colors_name = "hatsune-miku-light"

local groups = {
  ["Normal"] = { fg = "#753826", bg = "#F5F0E2" },
  ["NormalFloat"] = { fg = "#753826", bg = "#C7E1EE" },
  ["NormalNC"] = { fg = "#753826", bg = "#F5F0E2" },
  ["Cursor"] = { fg = "#F5F0E2", bg = "#E88493" },
  ["lCursor"] = { link = "Cursor" },
  ["CursorIM"] = { fg = "#F5F0E2", bg = "#4E9CA1" },
  ["TermCursor"] = { fg = "#F5F0E2", bg = "#E88493" },
  ["TermCursorNC"] = { fg = "#F5F0E2", bg = "#8B8E90" },
  ["CursorLine"] = { bg = "#D5EAF4" },
  ["CursorColumn"] = { bg = "#D5EAF4" },
  ["CursorLineNr"] = { fg = "#4E9CA1", bold = true },
  ["CursorLineFold"] = { fg = "#8B8E90", bg = "#D5EAF4" },
  ["CursorLineSign"] = { bg = "#D5EAF4" },
  ["ColorColumn"] = { bg = "#D5EAF4" },
  ["LineNr"] = { fg = "#8B8E90" },
  ["LineNrAbove"] = { link = "LineNr" },
  ["LineNrBelow"] = { link = "LineNr" },
  ["SignColumn"] = { fg = "#8B8E90", bg = "#F5F0E2" },
  ["FoldColumn"] = { fg = "#8B8E90", bg = "#F5F0E2" },
  ["Folded"] = { fg = "#646A6D", bg = "#D5EAF4" },
  ["VertSplit"] = { fg = "#6F848E" },
  ["WinSeparator"] = { fg = "#6F848E" },
  ["StatusLine"] = { fg = "#753826", bg = "#D5EAF4" },
  ["StatusLineNC"] = { fg = "#646A6D", bg = "#D5EAF4" },
  ["TabLine"] = { fg = "#646A6D", bg = "#FEFAF0" },
  ["TabLineFill"] = { bg = "#FEFAF0" },
  ["TabLineSel"] = { fg = "#753826", bg = "#F5F0E2", bold = true },
  ["WinBar"] = { fg = "#753826", bg = "#D5EAF4" },
  ["WinBarNC"] = { fg = "#646A6D", bg = "#D5EAF4" },
  ["Pmenu"] = { fg = "#753826", bg = "#C7E1EE" },
  ["PmenuSel"] = { fg = "#753826", bg = "#C6DAD9" },
  ["PmenuSbar"] = { bg = "#D5EAF4" },
  ["PmenuThumb"] = { bg = "#4E9CA1" },
  ["PmenuMatch"] = { fg = "#4E9CA1" },
  ["PmenuMatchSel"] = { fg = "#4E9CA1", bg = "#C6DAD9" },
  ["PmenuKind"] = { fg = "#646A6D", bg = "#C7E1EE" },
  ["PmenuKindSel"] = { fg = "#646A6D", bg = "#C6DAD9" },
  ["PmenuExtra"] = { fg = "#8B8E90", bg = "#C7E1EE" },
  ["PmenuExtraSel"] = { fg = "#8B8E90", bg = "#C6DAD9" },
  ["FloatBorder"] = { fg = "#6F848E", bg = "#C7E1EE" },
  ["FloatTitle"] = { fg = "#4E9CA1", bg = "#C7E1EE", bold = true },
  ["FloatFooter"] = { fg = "#646A6D", bg = "#C7E1EE" },
  ["Search"] = { fg = "#F5F0E2", bg = "#896700" },
  ["IncSearch"] = { fg = "#F5F0E2", bg = "#4E9CA1" },
  ["CurSearch"] = { fg = "#F5F0E2", bg = "#E88493" },
  ["Substitute"] = { fg = "#F5F0E2", bg = "#B04C00" },
  ["Visual"] = { bg = "#C6DAD9" },
  ["VisualNOS"] = { bg = "#C6DAD9" },
  ["MatchParen"] = { fg = "#E88493", bold = true },
  ["DiffAdd"] = { bg = "#D1DFCD" },
  ["DiffChange"] = { bg = "#E8D8C1" },
  ["DiffDelete"] = { bg = "#E3CDD9" },
  ["DiffText"] = { bg = "#DEC6A9" },
  ["Added"] = { fg = "#007954" },
  ["Changed"] = { fg = "#9B4900" },
  ["Removed"] = { fg = "#7900A4" },
  ["ErrorMsg"] = { fg = "#BF0028" },
  ["WarningMsg"] = { fg = "#B04C00" },
  ["MoreMsg"] = { fg = "#4E9CA1" },
  ["Question"] = { fg = "#4E9CA1" },
  ["ModeMsg"] = { fg = "#646A6D", bold = true },
  ["MsgArea"] = { fg = "#753826" },
  ["Directory"] = { fg = "#4E9CA1" },
  ["Title"] = { fg = "#4E9CA1", bold = true },
  ["NonText"] = { fg = "#8B8E90" },
  ["EndOfBuffer"] = { fg = "#8B8E90" },
  ["Whitespace"] = { fg = "#919496" },
  ["SpecialKey"] = { fg = "#8B8E90" },
  ["Conceal"] = { fg = "#646A6D" },
  ["WildMenu"] = { fg = "#F5F0E2", bg = "#4E9CA1" },
  ["QuickFixLine"] = { bg = "#C6DAD9" },
  ["SnippetTabstop"] = { bg = "#C6DAD9" },
  ["SpellBad"] = { sp = "#BF0028", undercurl = true },
  ["SpellCap"] = { sp = "#B04C00", undercurl = true },
  ["SpellRare"] = { sp = "#008595", undercurl = true },
  ["SpellLocal"] = { sp = "#008595", undercurl = true },
  ["Comment"] = { fg = "#578F92", italic = true },
  ["Constant"] = { fg = "#0058A3" },
  ["String"] = { fg = "#00791B" },
  ["Character"] = { fg = "#00791B" },
  ["Number"] = { fg = "#0058A3" },
  ["Boolean"] = { fg = "#0058A3" },
  ["Float"] = { fg = "#0058A3" },
  ["Identifier"] = { fg = "#5849CB" },
  ["Function"] = { fg = "#896700" },
  ["Statement"] = { fg = "#007284" },
  ["Conditional"] = { fg = "#007284" },
  ["Repeat"] = { fg = "#007284" },
  ["Label"] = { fg = "#007284" },
  ["Operator"] = { fg = "#B80067" },
  ["Keyword"] = { fg = "#007284" },
  ["Exception"] = { fg = "#007284" },
  ["PreProc"] = { fg = "#A90095" },
  ["Include"] = { fg = "#007284" },
  ["Define"] = { fg = "#A90095" },
  ["Macro"] = { fg = "#A90095" },
  ["PreCondit"] = { fg = "#A90095" },
  ["Type"] = { fg = "#8B12BA" },
  ["StorageClass"] = { fg = "#007284" },
  ["Structure"] = { fg = "#346900" },
  ["Typedef"] = { fg = "#8B12BA" },
  ["Special"] = { fg = "#AA4200" },
  ["SpecialChar"] = { fg = "#AA4200" },
  ["Tag"] = { fg = "#896700" },
  ["Delimiter"] = { fg = "#00878E" },
  ["SpecialComment"] = { fg = "#498083", italic = true },
  ["Debug"] = { fg = "#B04C00" },
  ["Underlined"] = { fg = "#006679", underline = true },
  ["Error"] = { fg = "#BF0028" },
  ["Todo"] = { fg = "#4E9CA1", bold = true },
  ["@keyword"] = { fg = "#007284" },
  ["@keyword.coroutine"] = { fg = "#007284" },
  ["@keyword.function"] = { fg = "#007284" },
  ["@keyword.operator"] = { fg = "#B80067" },
  ["@keyword.import"] = { fg = "#007284" },
  ["@keyword.type"] = { fg = "#007284" },
  ["@keyword.modifier"] = { fg = "#007284" },
  ["@keyword.repeat"] = { fg = "#007284" },
  ["@keyword.return"] = { fg = "#007284" },
  ["@keyword.debug"] = { fg = "#007284" },
  ["@keyword.exception"] = { fg = "#007284" },
  ["@keyword.conditional"] = { fg = "#007284" },
  ["@keyword.conditional.ternary"] = { fg = "#B80067" },
  ["@keyword.directive"] = { fg = "#A90095" },
  ["@keyword.directive.define"] = { fg = "#A90095" },
  ["@keyword.storage"] = { fg = "#007284" },
  ["@variable"] = { fg = "#5849CB" },
  ["@variable.builtin"] = { fg = "#007284", italic = true },
  ["@variable.parameter"] = { fg = "#AA4200" },
  ["@variable.parameter.builtin"] = { fg = "#AA4200", italic = true },
  ["@variable.member"] = { fg = "#AA4200" },
  ["@constant"] = { fg = "#0058A3" },
  ["@constant.builtin"] = { fg = "#0058A3" },
  ["@constant.macro"] = { fg = "#A90095" },
  ["@module"] = { fg = "#8B12BA" },
  ["@module.builtin"] = { fg = "#8B12BA", italic = true },
  ["@label"] = { fg = "#007284" },
  ["@string"] = { fg = "#00791B" },
  ["@string.documentation"] = { fg = "#498083" },
  ["@string.regexp"] = { fg = "#00791B" },
  ["@string.escape"] = { fg = "#AA4200" },
  ["@string.special"] = { fg = "#00791B" },
  ["@string.special.symbol"] = { fg = "#0058A3" },
  ["@string.special.url"] = { fg = "#006679", underline = true },
  ["@string.special.path"] = { fg = "#00791B" },
  ["@character"] = { fg = "#00791B" },
  ["@character.special"] = { fg = "#AA4200" },
  ["@number"] = { fg = "#0058A3" },
  ["@number.float"] = { fg = "#0058A3" },
  ["@boolean"] = { fg = "#0058A3" },
  ["@type"] = { fg = "#8B12BA" },
  ["@type.builtin"] = { fg = "#8B12BA" },
  ["@type.definition"] = { fg = "#7B5393" },
  ["@type.qualifier"] = { fg = "#007284" },
  ["@attribute"] = { fg = "#A90095" },
  ["@attribute.builtin"] = { fg = "#A90095" },
  ["@property"] = { fg = "#AA4200" },
  ["@function"] = { fg = "#896700" },
  ["@function.builtin"] = { fg = "#764A00" },
  ["@function.call"] = { fg = "#896700" },
  ["@function.macro"] = { fg = "#A90095" },
  ["@function.method"] = { fg = "#896700" },
  ["@function.method.call"] = { fg = "#896700" },
  ["@constructor"] = { fg = "#346900" },
  ["@operator"] = { fg = "#B80067" },
  ["@punctuation.delimiter"] = { fg = "#00878E" },
  ["@punctuation.bracket"] = { fg = "#00878E" },
  ["@punctuation.special"] = { fg = "#00878E" },
  ["@comment"] = { fg = "#578F92", italic = true },
  ["@comment.documentation"] = { fg = "#498083", italic = true },
  ["@comment.error"] = { fg = "#BF0028" },
  ["@comment.warning"] = { fg = "#B04C00" },
  ["@comment.todo"] = { fg = "#4E9CA1", bold = true },
  ["@comment.note"] = { fg = "#008595" },
  ["@markup.strong"] = { bold = true },
  ["@markup.italic"] = { italic = true },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.underline"] = { underline = true },
  ["@markup.heading"] = { fg = "#764A00", bold = true },
  ["@markup.heading.1"] = { fg = "#764A00", bold = true },
  ["@markup.heading.2"] = { fg = "#764A00", bold = true },
  ["@markup.heading.3"] = { fg = "#764A00", bold = true },
  ["@markup.heading.4"] = { fg = "#764A00", bold = true },
  ["@markup.heading.5"] = { fg = "#764A00", bold = true },
  ["@markup.heading.6"] = { fg = "#764A00", bold = true },
  ["@markup.quote"] = { fg = "#005D9F", italic = true },
  ["@markup.math"] = { fg = "#0058A3" },
  ["@markup.environment"] = { fg = "#A90095" },
  ["@markup.link"] = { fg = "#006679" },
  ["@markup.link.label"] = { fg = "#006679" },
  ["@markup.link.url"] = { fg = "#71009C", underline = true },
  ["@markup.raw"] = { fg = "#005AB3" },
  ["@markup.raw.block"] = { fg = "#005AB3" },
  ["@markup.list"] = { fg = "#00878E" },
  ["@markup.list.checked"] = { fg = "#008A63" },
  ["@markup.list.unchecked"] = { fg = "#646A6D" },
  ["@diff.plus"] = { fg = "#007954" },
  ["@diff.minus"] = { fg = "#7900A4" },
  ["@diff.delta"] = { fg = "#9B4900" },
  ["@tag"] = { fg = "#896700" },
  ["@tag.builtin"] = { fg = "#896700" },
  ["@tag.attribute"] = { fg = "#AA4200" },
  ["@tag.delimiter"] = { fg = "#00878E" },
  ["@lsp.type.namespace"] = { fg = "#8B12BA" },
  ["@lsp.type.type"] = { fg = "#8B12BA" },
  ["@lsp.type.class"] = { fg = "#346900" },
  ["@lsp.type.enum"] = { fg = "#346900" },
  ["@lsp.type.interface"] = { fg = "#007D57" },
  ["@lsp.type.struct"] = { fg = "#346900" },
  ["@lsp.type.typeParameter"] = { fg = "#7B5393" },
  ["@lsp.type.parameter"] = { fg = "#AA4200" },
  ["@lsp.type.variable"] = { fg = "#5849CB" },
  ["@lsp.type.property"] = { fg = "#AA4200" },
  ["@lsp.type.enumMember"] = { fg = "#0058A3" },
  ["@lsp.type.function"] = { fg = "#896700" },
  ["@lsp.type.method"] = { fg = "#896700" },
  ["@lsp.type.macro"] = { fg = "#A90095" },
  ["@lsp.type.keyword"] = { fg = "#007284" },
  ["@lsp.type.modifier"] = { fg = "#007284" },
  ["@lsp.type.comment"] = { fg = "#578F92", italic = true },
  ["@lsp.type.string"] = { fg = "#00791B" },
  ["@lsp.type.number"] = { fg = "#0058A3" },
  ["@lsp.type.regexp"] = { fg = "#00791B" },
  ["@lsp.type.operator"] = { fg = "#B80067" },
  ["@lsp.type.decorator"] = { fg = "#A90095" },
  ["@lsp.mod.deprecated"] = { strikethrough = true },
  ["@lsp.typemod.function.defaultLibrary"] = { fg = "#764A00" },
  ["@lsp.typemod.variable.defaultLibrary"] = { fg = "#007284", italic = true },
  ["LspReferenceText"] = { bg = "#DDE4D9" },
  ["LspReferenceRead"] = { bg = "#DDE4D9" },
  ["LspReferenceWrite"] = { bg = "#CBDBD2" },
  ["LspInlayHint"] = { fg = "#8B8E90", italic = true },
  ["LspCodeLens"] = { fg = "#8B8E90" },
  ["LspSignatureActiveParameter"] = { fg = "#4E9CA1", bold = true },
  ["DiagnosticError"] = { fg = "#BF0028" },
  ["DiagnosticWarn"] = { fg = "#B04C00" },
  ["DiagnosticInfo"] = { fg = "#008595" },
  ["DiagnosticHint"] = { fg = "#4E9CA1" },
  ["DiagnosticOk"] = { fg = "#008A63" },
  ["DiagnosticUnnecessary"] = { fg = "#8B8E90" },
  ["DiagnosticDeprecated"] = { strikethrough = true },
  ["DiagnosticVirtualTextError"] = { fg = "#BF0028", bg = "#F1DCD3" },
  ["DiagnosticVirtualTextWarn"] = { fg = "#B04C00", bg = "#EFE2CF" },
  ["DiagnosticVirtualTextInfo"] = { fg = "#008595", bg = "#E1E7DC" },
  ["DiagnosticVirtualTextHint"] = { fg = "#4E9CA1", bg = "#E7E9DD" },
  ["DiagnosticVirtualTextOk"] = { fg = "#008A63", bg = "#E1E8D8" },
  ["DiagnosticUnderlineError"] = { sp = "#BF0028", undercurl = true },
  ["DiagnosticUnderlineWarn"] = { sp = "#B04C00", undercurl = true },
  ["DiagnosticUnderlineInfo"] = { sp = "#008595", undercurl = true },
  ["DiagnosticUnderlineHint"] = { sp = "#4E9CA1", undercurl = true },
  ["DiagnosticUnderlineOk"] = { sp = "#008A63", undercurl = true },
  ["DiagnosticSignError"] = { fg = "#BF0028" },
  ["DiagnosticSignWarn"] = { fg = "#B04C00" },
  ["DiagnosticSignInfo"] = { fg = "#008595" },
  ["DiagnosticSignHint"] = { fg = "#4E9CA1" },
  ["DiagnosticSignOk"] = { fg = "#008A63" },
  ["DiagnosticFloatingError"] = { fg = "#BF0028", bg = "#C7E1EE" },
  ["DiagnosticFloatingWarn"] = { fg = "#B04C00", bg = "#C7E1EE" },
  ["DiagnosticFloatingInfo"] = { fg = "#008595", bg = "#C7E1EE" },
  ["DiagnosticFloatingHint"] = { fg = "#4E9CA1", bg = "#C7E1EE" },
  ["DiagnosticFloatingOk"] = { fg = "#008A63", bg = "#C7E1EE" },
  ["healthError"] = { fg = "#BF0028" },
  ["healthWarning"] = { fg = "#B04C00" },
  ["healthSuccess"] = { fg = "#008A63" },
  ["GitSignsAdd"] = { fg = "#007954" },
  ["GitSignsChange"] = { fg = "#9B4900" },
  ["GitSignsDelete"] = { fg = "#7900A4" },
  ["GitSignsAddNr"] = { fg = "#007954" },
  ["GitSignsChangeNr"] = { fg = "#9B4900" },
  ["GitSignsDeleteNr"] = { fg = "#7900A4" },
  ["GitSignsAddLn"] = { bg = "#E1E6D6" },
  ["GitSignsChangeLn"] = { bg = "#EEE2CF" },
  ["GitSignsDeleteLn"] = { bg = "#EBDCDD" },
  ["GitSignsAddInline"] = { bg = "#D1DFCD" },
  ["GitSignsChangeInline"] = { bg = "#E8D8C1" },
  ["GitSignsDeleteInline"] = { bg = "#E3CDD9" },
  ["GitSignsCurrentLineBlame"] = { fg = "#8B8E90", italic = true },
  ["TelescopeNormal"] = { fg = "#753826", bg = "#C7E1EE" },
  ["TelescopeBorder"] = { fg = "#6F848E", bg = "#C7E1EE" },
  ["TelescopeTitle"] = { fg = "#4E9CA1", bold = true },
  ["TelescopeSelection"] = { bg = "#C6DAD9" },
  ["TelescopeSelectionCaret"] = { fg = "#E88493" },
  ["TelescopeMatching"] = { fg = "#4E9CA1", bold = true },
  ["TelescopePromptPrefix"] = { fg = "#4E9CA1" },
  ["TelescopePromptNormal"] = { fg = "#753826", bg = "#C7E1EE" },
  ["TelescopePromptBorder"] = { fg = "#6F848E", bg = "#C7E1EE" },
  ["TelescopePromptTitle"] = { fg = "#4E9CA1", bold = true },
  ["TelescopePreviewNormal"] = { fg = "#753826", bg = "#C7E1EE" },
  ["TelescopePreviewBorder"] = { fg = "#6F848E", bg = "#C7E1EE" },
  ["TelescopePreviewTitle"] = { fg = "#4E9CA1", bold = true },
  ["TelescopeResultsNormal"] = { fg = "#753826", bg = "#C7E1EE" },
  ["TelescopeResultsBorder"] = { fg = "#6F848E", bg = "#C7E1EE" },
  ["TelescopeResultsTitle"] = { fg = "#4E9CA1", bold = true },
  ["CmpItemAbbr"] = { fg = "#753826" },
  ["CmpItemAbbrDeprecated"] = { fg = "#8B8E90", strikethrough = true },
  ["CmpItemAbbrMatch"] = { fg = "#4E9CA1", bold = true },
  ["CmpItemAbbrMatchFuzzy"] = { fg = "#4E9CA1" },
  ["CmpItemKind"] = { fg = "#646A6D" },
  ["CmpItemMenu"] = { fg = "#8B8E90" },
  ["CmpItemKindText"] = { fg = "#753826" },
  ["CmpItemKindMethod"] = { fg = "#896700" },
  ["CmpItemKindFunction"] = { fg = "#896700" },
  ["CmpItemKindConstructor"] = { fg = "#346900" },
  ["CmpItemKindField"] = { fg = "#AA4200" },
  ["CmpItemKindVariable"] = { fg = "#5849CB" },
  ["CmpItemKindClass"] = { fg = "#346900" },
  ["CmpItemKindInterface"] = { fg = "#007D57" },
  ["CmpItemKindModule"] = { fg = "#8B12BA" },
  ["CmpItemKindProperty"] = { fg = "#AA4200" },
  ["CmpItemKindUnit"] = { fg = "#0058A3" },
  ["CmpItemKindValue"] = { fg = "#0058A3" },
  ["CmpItemKindEnum"] = { fg = "#346900" },
  ["CmpItemKindKeyword"] = { fg = "#007284" },
  ["CmpItemKindSnippet"] = { fg = "#4E9CA1" },
  ["CmpItemKindColor"] = { fg = "#4E9CA1" },
  ["CmpItemKindFile"] = { fg = "#753826" },
  ["CmpItemKindReference"] = { fg = "#0058A3" },
  ["CmpItemKindFolder"] = { fg = "#4E9CA1" },
  ["CmpItemKindEnumMember"] = { fg = "#0058A3" },
  ["CmpItemKindConstant"] = { fg = "#0058A3" },
  ["CmpItemKindStruct"] = { fg = "#346900" },
  ["CmpItemKindEvent"] = { fg = "#007284" },
  ["CmpItemKindOperator"] = { fg = "#B80067" },
  ["CmpItemKindTypeParameter"] = { fg = "#7B5393" },
  ["IblIndent"] = { fg = "#8B8E90", nocombine = true },
  ["IblScope"] = { fg = "#4E9CA1", nocombine = true },
  ["IblWhitespace"] = { fg = "#919496", nocombine = true },
  ["IndentBlanklineChar"] = { fg = "#8B8E90", nocombine = true },
  ["IndentBlanklineContextChar"] = { fg = "#4E9CA1", nocombine = true },
  ["NeoTreeNormal"] = { fg = "#753826", bg = "#D5EAF4" },
  ["NeoTreeNormalNC"] = { fg = "#753826", bg = "#D5EAF4" },
  ["NeoTreeDimText"] = { fg = "#8B8E90" },
  ["NeoTreeFileName"] = { fg = "#753826" },
  ["NeoTreeFileIcon"] = { fg = "#646A6D" },
  ["NeoTreeDirectoryName"] = { fg = "#4E9CA1" },
  ["NeoTreeDirectoryIcon"] = { fg = "#4E9CA1" },
  ["NeoTreeRootName"] = { fg = "#4E9CA1", bold = true },
  ["NeoTreeGitAdded"] = { fg = "#007954" },
  ["NeoTreeGitModified"] = { fg = "#9B4900" },
  ["NeoTreeGitDeleted"] = { fg = "#7900A4" },
  ["NeoTreeGitConflict"] = { fg = "#A6005A" },
  ["NeoTreeGitUntracked"] = { fg = "#007C8C" },
  ["NeoTreeGitRenamed"] = { fg = "#443D9E" },
  ["NeoTreeIndentMarker"] = { fg = "#8B8E90" },
  ["NeoTreeWinSeparator"] = { fg = "#6F848E", bg = "#D5EAF4" },
  ["NeoTreeCursorLine"] = { bg = "#C6DAD9" },
  ["NvimTreeNormal"] = { fg = "#753826", bg = "#D5EAF4" },
  ["NvimTreeNormalNC"] = { fg = "#753826", bg = "#D5EAF4" },
  ["NvimTreeRootFolder"] = { fg = "#4E9CA1", bold = true },
  ["NvimTreeFolderIcon"] = { fg = "#4E9CA1" },
  ["NvimTreeFolderName"] = { fg = "#4E9CA1" },
  ["NvimTreeOpenedFolderName"] = { fg = "#4E9CA1" },
  ["NvimTreeEmptyFolderName"] = { fg = "#646A6D" },
  ["NvimTreeGitDirty"] = { fg = "#9B4900" },
  ["NvimTreeGitNew"] = { fg = "#007954" },
  ["NvimTreeGitDeleted"] = { fg = "#7900A4" },
  ["NvimTreeGitRenamed"] = { fg = "#443D9E" },
  ["NvimTreeIndentMarker"] = { fg = "#8B8E90" },
  ["NvimTreeWinSeparator"] = { fg = "#6F848E" },
  ["NvimTreeCursorLine"] = { bg = "#C6DAD9" },
  ["NvimTreeSpecialFile"] = { fg = "#A90095" },
  ["BufferLineFill"] = { bg = "#FEFAF0" },
  ["BufferLineBackground"] = { fg = "#646A6D", bg = "#D5EAF4" },
  ["BufferLineBuffer"] = { fg = "#646A6D", bg = "#D5EAF4" },
  ["BufferLineBufferSelected"] = { fg = "#753826", bg = "#F5F0E2", bold = true },
  ["BufferLineBufferVisible"] = { fg = "#646A6D", bg = "#D5EAF4" },
  ["BufferLineTab"] = { fg = "#646A6D", bg = "#D5EAF4" },
  ["BufferLineTabSelected"] = { fg = "#753826", bg = "#F5F0E2" },
  ["BufferLineTabSeparator"] = { fg = "#FEFAF0", bg = "#D5EAF4" },
  ["BufferLineTabSeparatorSelected"] = { fg = "#FEFAF0", bg = "#F5F0E2" },
  ["BufferLineSeparator"] = { fg = "#FEFAF0", bg = "#D5EAF4" },
  ["BufferLineSeparatorSelected"] = { fg = "#FEFAF0", bg = "#F5F0E2" },
  ["BufferLineIndicatorSelected"] = { fg = "#4E9CA1" },
  ["BufferLineModified"] = { fg = "#9B4900" },
  ["BufferLineModifiedSelected"] = { fg = "#9B4900" },
  ["BufferLineModifiedVisible"] = { fg = "#9B4900" },
  ["BufferLineError"] = { fg = "#BF0028" },
  ["BufferLineErrorSelected"] = { fg = "#BF0028" },
  ["BufferLineWarning"] = { fg = "#B04C00" },
  ["BufferLineWarningSelected"] = { fg = "#B04C00" },
  ["WhichKey"] = { fg = "#4E9CA1" },
  ["WhichKeyGroup"] = { fg = "#00717F" },
  ["WhichKeyDesc"] = { fg = "#753826" },
  ["WhichKeySeparator"] = { fg = "#8B8E90" },
  ["WhichKeyFloat"] = { bg = "#C7E1EE" },
  ["WhichKeyBorder"] = { fg = "#6F848E", bg = "#C7E1EE" },
  ["WhichKeyValue"] = { fg = "#646A6D" },
  ["TroubleNormal"] = { fg = "#753826", bg = "#D5EAF4" },
  ["TroubleNormalNC"] = { fg = "#753826", bg = "#D5EAF4" },
  ["TroubleCount"] = { fg = "#4E9CA1", bold = true },
  ["TroubleText"] = { fg = "#753826" },
  ["TroubleIndent"] = { fg = "#8B8E90" },
  ["TroubleLocation"] = { fg = "#646A6D" },
  ["TroubleFile"] = { fg = "#4E9CA1" },
  ["TroubleFoldIcon"] = { fg = "#646A6D" },
  ["TroubleCode"] = { fg = "#646A6D" },
  ["FlashLabel"] = { fg = "#F5F0E2", bg = "#E88493", bold = true },
  ["FlashMatch"] = { fg = "#4E9CA1" },
  ["FlashCurrent"] = { fg = "#F5F0E2", bg = "#4E9CA1" },
  ["FlashBackdrop"] = { fg = "#8B8E90" },
  ["LeapMatch"] = { fg = "#4E9CA1", bold = true },
  ["LeapLabelPrimary"] = { fg = "#F5F0E2", bg = "#E88493", bold = true },
  ["LeapLabelSecondary"] = { fg = "#F5F0E2", bg = "#00717F" },
  ["LeapBackdrop"] = { fg = "#8B8E90" },
  ["LazyNormal"] = { fg = "#753826", bg = "#C7E1EE" },
  ["LazyButton"] = { fg = "#753826", bg = "#D5EAF4" },
  ["LazyButtonActive"] = { fg = "#F5F0E2", bg = "#4E9CA1", bold = true },
  ["LazyH1"] = { fg = "#F5F0E2", bg = "#4E9CA1", bold = true },
  ["LazyH2"] = { fg = "#4E9CA1", bold = true },
  ["LazyComment"] = { fg = "#646A6D" },
  ["LazyDimmed"] = { fg = "#8B8E90" },
  ["LazyProp"] = { fg = "#4E9CA1" },
  ["LazyValue"] = { fg = "#00791B" },
  ["LazyReasonPlugin"] = { fg = "#4E9CA1" },
  ["LazyReasonEvent"] = { fg = "#007284" },
  ["LazyReasonStart"] = { fg = "#008A63" },
  ["LazyReasonCmd"] = { fg = "#896700" },
  ["LazyReasonFt"] = { fg = "#8B12BA" },
  ["LazySpecial"] = { fg = "#E88493" },
  ["LazyProgressDone"] = { fg = "#4E9CA1" },
  ["LazyProgressTodo"] = { fg = "#8B8E90" },
  ["MasonNormal"] = { fg = "#753826", bg = "#C7E1EE" },
  ["MasonHeader"] = { fg = "#F5F0E2", bg = "#4E9CA1", bold = true },
  ["MasonHighlight"] = { fg = "#4E9CA1" },
  ["MasonHighlightBlock"] = { fg = "#F5F0E2", bg = "#4E9CA1" },
  ["MasonHighlightBlockBold"] = { fg = "#F5F0E2", bg = "#4E9CA1", bold = true },
  ["MasonMuted"] = { fg = "#646A6D" },
  ["MasonMutedBlock"] = { fg = "#646A6D", bg = "#D5EAF4" },
  ["NotifyERRORBorder"] = { fg = "#BF0028" },
  ["NotifyERRORTitle"] = { fg = "#BF0028" },
  ["NotifyERRORIcon"] = { fg = "#BF0028" },
  ["NotifyWARNBorder"] = { fg = "#B04C00" },
  ["NotifyWARNTitle"] = { fg = "#B04C00" },
  ["NotifyWARNIcon"] = { fg = "#B04C00" },
  ["NotifyINFOBorder"] = { fg = "#008595" },
  ["NotifyINFOTitle"] = { fg = "#008595" },
  ["NotifyINFOIcon"] = { fg = "#008595" },
  ["NotifyDEBUGBorder"] = { fg = "#646A6D" },
  ["NotifyDEBUGTitle"] = { fg = "#646A6D" },
  ["NotifyDEBUGIcon"] = { fg = "#646A6D" },
  ["NotifyTRACEBorder"] = { fg = "#8B8E90" },
  ["NotifyTRACETitle"] = { fg = "#8B8E90" },
  ["NotifyTRACEIcon"] = { fg = "#8B8E90" },
  ["NotifyBackground"] = { bg = "#C7E1EE" },
  ["NoiceCmdline"] = { fg = "#753826" },
  ["NoiceCmdlinePopup"] = { fg = "#753826", bg = "#C7E1EE" },
  ["NoiceCmdlinePopupBorder"] = { fg = "#6F848E" },
  ["NoiceCmdlineIcon"] = { fg = "#4E9CA1" },
  ["NoiceConfirm"] = { fg = "#753826", bg = "#C7E1EE" },
  ["NoiceConfirmBorder"] = { fg = "#6F848E" },
  ["NoiceMini"] = { fg = "#753826", bg = "#C7E1EE" },
  ["NoiceFormatProgressDone"] = { fg = "#F5F0E2", bg = "#4E9CA1" },
  ["NoiceFormatProgressTodo"] = { fg = "#753826", bg = "#D5EAF4" },
  ["DashboardHeader"] = { fg = "#4E9CA1" },
  ["DashboardFooter"] = { fg = "#646A6D" },
  ["DashboardCenter"] = { fg = "#4E9CA1" },
  ["DashboardShortCut"] = { fg = "#E88493" },
  ["DashboardIcon"] = { fg = "#4E9CA1" },
  ["DashboardDesc"] = { fg = "#753826" },
  ["DashboardKey"] = { fg = "#E88493" },
  ["AlphaHeader"] = { fg = "#4E9CA1" },
  ["AlphaButtons"] = { fg = "#4E9CA1" },
  ["AlphaFooter"] = { fg = "#646A6D" },
  ["AlphaShortcut"] = { fg = "#E88493" },
  ["IlluminatedWordText"] = { bg = "#E7E9DD" },
  ["IlluminatedWordRead"] = { bg = "#DDE4D9" },
  ["IlluminatedWordWrite"] = { bg = "#CBDBD2" },
  ["NavicText"] = { fg = "#646A6D" },
  ["NavicSeparator"] = { fg = "#8B8E90" },
  ["NavicIconsFile"] = { fg = "#753826" },
  ["NavicIconsModule"] = { fg = "#8B12BA" },
  ["NavicIconsNamespace"] = { fg = "#8B12BA" },
  ["NavicIconsPackage"] = { fg = "#8B12BA" },
  ["NavicIconsClass"] = { fg = "#346900" },
  ["NavicIconsMethod"] = { fg = "#896700" },
  ["NavicIconsProperty"] = { fg = "#AA4200" },
  ["NavicIconsField"] = { fg = "#AA4200" },
  ["NavicIconsConstructor"] = { fg = "#346900" },
  ["NavicIconsEnum"] = { fg = "#346900" },
  ["NavicIconsInterface"] = { fg = "#007D57" },
  ["NavicIconsFunction"] = { fg = "#896700" },
  ["NavicIconsVariable"] = { fg = "#5849CB" },
  ["NavicIconsConstant"] = { fg = "#0058A3" },
  ["NavicIconsString"] = { fg = "#00791B" },
  ["NavicIconsNumber"] = { fg = "#0058A3" },
  ["NavicIconsBoolean"] = { fg = "#0058A3" },
  ["NavicIconsArray"] = { fg = "#00878E" },
  ["NavicIconsObject"] = { fg = "#8B12BA" },
  ["NavicIconsKey"] = { fg = "#AA4200" },
  ["NavicIconsNull"] = { fg = "#0058A3" },
  ["NavicIconsEnumMember"] = { fg = "#0058A3" },
  ["NavicIconsStruct"] = { fg = "#346900" },
  ["NavicIconsEvent"] = { fg = "#007284" },
  ["NavicIconsOperator"] = { fg = "#B80067" },
  ["NavicIconsTypeParameter"] = { fg = "#7B5393" },
  ["MiniStatuslineDevinfo"] = { fg = "#646A6D", bg = "#D5EAF4" },
  ["MiniStatuslineFileinfo"] = { fg = "#646A6D", bg = "#D5EAF4" },
  ["MiniStatuslineFilename"] = { fg = "#753826", bg = "#D5EAF4" },
  ["MiniStatuslineInactive"] = { fg = "#646A6D", bg = "#D5EAF4" },
  ["MiniStatuslineModeNormal"] = { fg = "#F5F0E2", bg = "#4E9CA1", bold = true },
  ["MiniStatuslineModeInsert"] = { fg = "#F5F0E2", bg = "#008A63", bold = true },
  ["MiniStatuslineModeVisual"] = { fg = "#F5F0E2", bg = "#E88493", bold = true },
  ["MiniStatuslineModeReplace"] = { fg = "#F5F0E2", bg = "#BF0028", bold = true },
  ["MiniStatuslineModeCommand"] = { fg = "#F5F0E2", bg = "#B04C00", bold = true },
  ["MiniStatuslineModeOther"] = { fg = "#F5F0E2", bg = "#00717F", bold = true },
  ["MiniTablineCurrent"] = { fg = "#753826", bg = "#F5F0E2", bold = true },
  ["MiniTablineVisible"] = { fg = "#646A6D", bg = "#D5EAF4" },
  ["MiniTablineHidden"] = { fg = "#8B8E90", bg = "#D5EAF4" },
  ["MiniTablineModifiedCurrent"] = { fg = "#9B4900", bg = "#F5F0E2" },
  ["MiniTablineModifiedVisible"] = { fg = "#9B4900", bg = "#D5EAF4" },
  ["MiniTablineModifiedHidden"] = { fg = "#9B4900", bg = "#D5EAF4" },
  ["MiniTablineFill"] = { bg = "#FEFAF0" },
  ["MiniTablineTabpagesection"] = { fg = "#F5F0E2", bg = "#4E9CA1", bold = true },
  ["MiniCursorword"] = { bg = "#DDE4D9" },
  ["MiniCursorwordCurrent"] = { bg = "#DDE4D9" },
  ["MiniIndentscopeSymbol"] = { fg = "#4E9CA1" },
  ["MiniJump"] = { fg = "#F5F0E2", bg = "#E88493" },
  ["MiniJump2dSpot"] = { fg = "#E88493", bold = true },
  ["MiniSurround"] = { fg = "#F5F0E2", bg = "#4E9CA1" },
  ["MiniTrailspace"] = { bg = "#BF0028" },
  ["MiniDiffSignAdd"] = { fg = "#007954" },
  ["MiniDiffSignChange"] = { fg = "#9B4900" },
  ["MiniDiffSignDelete"] = { fg = "#7900A4" },
  ["MiniPickNormal"] = { fg = "#753826", bg = "#C7E1EE" },
  ["MiniPickBorder"] = { fg = "#6F848E", bg = "#C7E1EE" },
  ["MiniPickPrompt"] = { fg = "#4E9CA1" },
  ["MiniPickMatchCurrent"] = { bg = "#C6DAD9" },
  ["MiniPickMatchMarked"] = { fg = "#4E9CA1", bold = true },
  ["MiniPickMatchRanges"] = { fg = "#4E9CA1" },
  ["GitSignsAddPreview"] = { bg = "#D1DFCD" },
  ["GitSignsDeletePreview"] = { bg = "#E3CDD9" },
  ["DapBreakpoint"] = { fg = "#BF0028" },
  ["DapBreakpointCondition"] = { fg = "#B04C00" },
  ["DapBreakpointRejected"] = { fg = "#8B8E90" },
  ["DapLogPoint"] = { fg = "#008595" },
  ["DapStopped"] = { fg = "#B04C00", bg = "#EFE2CF" },
  ["DapStoppedLine"] = { bg = "#EFE2CF" },
  ["DapUIScope"] = { fg = "#4E9CA1" },
  ["DapUIType"] = { fg = "#8B12BA" },
  ["DapUIValue"] = { fg = "#0058A3" },
  ["DapUIVariable"] = { fg = "#5849CB" },
  ["DapUIModifiedValue"] = { fg = "#B04C00", bold = true },
  ["DapUIDecoration"] = { fg = "#4E9CA1" },
  ["DapUIThread"] = { fg = "#008A63" },
  ["DapUIStoppedThread"] = { fg = "#B04C00" },
  ["DapUISource"] = { fg = "#00791B" },
  ["DapUILineNumber"] = { fg = "#8B8E90" },
  ["DapUIFloatBorder"] = { fg = "#6F848E" },
  ["DapUIWatchesEmpty"] = { fg = "#8B8E90" },
  ["DapUIWatchesValue"] = { fg = "#008A63" },
  ["DapUIWatchesError"] = { fg = "#BF0028" },
  ["DapUIBreakpointsPath"] = { fg = "#4E9CA1" },
  ["DapUIBreakpointsInfo"] = { fg = "#008595" },
  ["DapUIBreakpointsCurrentLine"] = { fg = "#008A63", bold = true },
  ["DapUIBreakpointsDisabledLine"] = { fg = "#8B8E90" },
  ["DapUICurrentFrameName"] = { fg = "#008A63", bold = true },
  ["DapUIPlayPause"] = { fg = "#008A63" },
  ["DapUIRestart"] = { fg = "#008A63" },
  ["DapUIStop"] = { fg = "#BF0028" },
  ["DapUIStepOver"] = { fg = "#4E9CA1" },
  ["DapUIStepInto"] = { fg = "#4E9CA1" },
  ["DapUIStepBack"] = { fg = "#4E9CA1" },
  ["DapUIStepOut"] = { fg = "#4E9CA1" },
  ["BlinkCmpMenu"] = { fg = "#753826", bg = "#C7E1EE" },
  ["BlinkCmpMenuBorder"] = { fg = "#6F848E", bg = "#C7E1EE" },
  ["BlinkCmpMenuSelection"] = { bg = "#C6DAD9" },
  ["BlinkCmpLabel"] = { fg = "#753826" },
  ["BlinkCmpLabelDeprecated"] = { fg = "#8B8E90", strikethrough = true },
  ["BlinkCmpLabelMatch"] = { fg = "#4E9CA1", bold = true },
  ["BlinkCmpKind"] = { fg = "#646A6D" },
  ["BlinkCmpKindText"] = { fg = "#753826" },
  ["BlinkCmpKindMethod"] = { fg = "#896700" },
  ["BlinkCmpKindFunction"] = { fg = "#896700" },
  ["BlinkCmpKindConstructor"] = { fg = "#346900" },
  ["BlinkCmpKindField"] = { fg = "#AA4200" },
  ["BlinkCmpKindVariable"] = { fg = "#5849CB" },
  ["BlinkCmpKindClass"] = { fg = "#346900" },
  ["BlinkCmpKindInterface"] = { fg = "#007D57" },
  ["BlinkCmpKindModule"] = { fg = "#8B12BA" },
  ["BlinkCmpKindProperty"] = { fg = "#AA4200" },
  ["BlinkCmpKindUnit"] = { fg = "#0058A3" },
  ["BlinkCmpKindValue"] = { fg = "#0058A3" },
  ["BlinkCmpKindEnum"] = { fg = "#346900" },
  ["BlinkCmpKindKeyword"] = { fg = "#007284" },
  ["BlinkCmpKindSnippet"] = { fg = "#4E9CA1" },
  ["BlinkCmpKindColor"] = { fg = "#4E9CA1" },
  ["BlinkCmpKindFile"] = { fg = "#753826" },
  ["BlinkCmpKindReference"] = { fg = "#0058A3" },
  ["BlinkCmpKindFolder"] = { fg = "#4E9CA1" },
  ["BlinkCmpKindEnumMember"] = { fg = "#0058A3" },
  ["BlinkCmpKindConstant"] = { fg = "#0058A3" },
  ["BlinkCmpKindStruct"] = { fg = "#346900" },
  ["BlinkCmpKindEvent"] = { fg = "#007284" },
  ["BlinkCmpKindOperator"] = { fg = "#B80067" },
  ["BlinkCmpKindTypeParameter"] = { fg = "#7B5393" },
  ["BlinkCmpDoc"] = { fg = "#753826", bg = "#C7E1EE" },
  ["BlinkCmpDocBorder"] = { fg = "#6F848E", bg = "#C7E1EE" },
  ["BlinkCmpDocSeparator"] = { fg = "#6F848E" },
  ["BlinkCmpSignatureHelp"] = { fg = "#753826", bg = "#C7E1EE" },
  ["BlinkCmpSignatureHelpBorder"] = { fg = "#6F848E", bg = "#C7E1EE" },
  ["BlinkCmpSignatureHelpActiveParameter"] = { fg = "#4E9CA1", bold = true },
  ["BlinkCmpGhostText"] = { fg = "#919496" },
  ["FidgetTitle"] = { fg = "#4E9CA1", bold = true },
  ["FidgetTask"] = { fg = "#646A6D" },
}

for group, hl in pairs(groups) do
  vim.api.nvim_set_hl(0, group, hl)
end

-- Terminal ANSI colors
vim.g.terminal_color_0 = "#AB9894"
vim.g.terminal_color_1 = "#BD0067"
vim.g.terminal_color_2 = "#467E00"
vim.g.terminal_color_3 = "#8F2B00"
vim.g.terminal_color_4 = "#005B9F"
vim.g.terminal_color_5 = "#7B00A7"
vim.g.terminal_color_6 = "#007D8D"
vim.g.terminal_color_7 = "#6E6B50"
vim.g.terminal_color_8 = "#746461"
vim.g.terminal_color_9 = "#9F0051"
vim.g.terminal_color_10 = "#407700"
vim.g.terminal_color_11 = "#8A2500"
vim.g.terminal_color_12 = "#004F91"
vim.g.terminal_color_13 = "#6F0099"
vim.g.terminal_color_14 = "#006E7E"
vim.g.terminal_color_15 = "#483430"
